function isCriticalEvent(e){if(e.classification?.critical===false)return false;if(e.review?.status==='false_positive')return false;return e.classification?.critical===true||Number(e.review?.level||e.level)>=12||!!e.diagnosis}
let eventClientSelection='';
'use strict';
const expandedDiagnoses=new Set();
let historyOffset=0,historyEventsData=null,historyQuery='',historyTimeFilter='',eventsLivePaused=false;
let deviceEditing=null,ruleEditing=null,blockEditing=null;
let snapshot, page='overview', timer, refreshHandle, refreshSeconds=5, preferencesLoaded=false;
const $=s=>document.querySelector(s);
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function toast(text){$('#toast').textContent=text;$('#toast').classList.remove('hidden');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.add('hidden'),7000)}
async function api(path,method='GET',body){const r=await fetch(path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':snapshot?.csrf||''},body:body===undefined?undefined:JSON.stringify(body)});if(r.status===401){location.href='/';throw Error('Sessão expirada')}if(!r.ok)throw Error(await r.text());return r.json()}
function date(t){return new Date(t).toLocaleString('pt-BR')}
function badge(level){return el('span',level>=12?'Crítico · '+level:level>=10?'Alto · '+level:level>=7?'Médio · '+level:'Baixo · '+level,'badge '+(level>=10?'high':level>=7?'medium':'muted'))}
function table(target,headers,rows){const box=$(target);box.replaceChildren();if(!rows.length){box.append(el('div','Nenhum registro nesta janela.','empty'));return}const t=el('table'),head=el('thead'),tr=el('tr');headers.forEach(h=>tr.append(el('th',h)));head.append(tr);t.append(head);const b=el('tbody');rows.forEach(row=>{const tr=el('tr');if(row.className)tr.className=row.className;row.forEach(x=>{const td=el('td');if(x instanceof Node)td.append(x);else td.textContent=x;tr.append(td)});b.append(tr)});t.append(b);box.append(t)}
function diagnosisPanel(d,model=false,id=""){const box=el('details',undefined,'diagnosis-panel');box.open=expandedDiagnoses.has(id);box.addEventListener('toggle',()=>{if(!box.isConnected)return;if(box.open)expandedDiagnoses.add(id);else expandedDiagnoses.delete(id)});box.append(el('summary',model?'Interpretação pelo Ollama · '+d.model:'Diagnóstico local · '+d.title));if(model)box.append(el('p',d.summary));box.append(el('p',d.cause));if(d.evidence)box.append(el('p','Evidência: '+d.evidence));for(const [title,items] of [['Verificações',d.checks],['Correção sugerida',d.remediation]]){if(items?.length){box.append(el('b',title));const list=el('ul');items.forEach(text=>list.append(el('li',text)));box.append(list)}}box.append(el('small',model?'Resposta de modelo generativo; confirme a causa e os procedimentos antes de agir. '+(d.uncertainty||''):d.uncertainty));if(d.research_status)box.append(el('small',d.research_status));for(const source of d.sources||[]){try{const u=new URL(source.url);if(u.protocol!=='https:')continue;const link=el('a',source.title||'Fonte consultada');link.href=u.href;link.target='_blank';link.rel='noopener noreferrer';box.append(link)}catch{}}if(d.reference){const url=new URL(d.reference);if(url.protocol==='https:'&&['cdn.kernel.org','openzfs.github.io','docs.netgate.com'].includes(url.hostname)){const link=el('a','Documentação de referência');link.href=url.href;link.target='_blank';link.rel='noopener noreferrer';box.append(link)}}return box}
function eventRows(evs){return evs.map(e=>{const manualCritical=e.review?.level>=12&&e.review?.status!=='false_positive',critical=isCriticalEvent(e);const desc=el('div',e.alert?(e.review?.title||e.rule):e.message);desc.append(el('small',(e.detector?e.detector+' · ':'')+(e.protocol?e.protocol+' · ':'')+(e.alert?e.message:e.kind)));if(e.review){const names={open:'Aberto',investigating:'Em investigação',resolved:'Resolvido',false_positive:'Falso positivo'};desc.append(el('small','Avaliação: '+names[e.review.status]+' · nível '+e.review.level));if(e.review.notes)desc.append(el('p',e.review.notes))}if(e.diagnosis)desc.append(diagnosisPanel(e.diagnosis,false,e.id+":base"));if(e.model_diagnosis)desc.append(diagnosisPanel(e.model_diagnosis,true,e.id+":model"));else if(critical){const ai=snapshot?.local_ai||{};desc.append(el("small",ai.ready?"Ollama · "+(ai.model||"modelo local")+": interpretação ainda não disponível. Fila geral: "+(ai.pending||0)+". Atualização automática.":"Ollama: "+(ai.status||"verificando disponibilidade")+". Este diagnóstico é da base de regras, sem interpretação generativa."))}if(e.cef)desc.append(el('small',e.cef.vendor+' / '+e.cef.product+' · '+e.cef.name+' · severidade CEF '+e.cef.severity+(e.cef.category?' · '+e.cef.category:'')));desc.className='message';const buttons=el('div');buttons.append(action('Criar regra',()=>draftRuleFromEvent(e)));if(snapshot?.role!=='viewer'){buttons.append(action(critical?'Configurar crítico e som':'Marcar como crítico',()=>openCriticalPatternDialog(e)));if(critical)buttons.append(action('Desmarcar como crítico',()=>clearCriticalPattern(e)));if(e.classification?.critical)buttons.append(action(e.classification.sound?'Desativar som desta descrição':'Ativar som desta descrição',()=>setCriticalPatternSound(e,!e.classification.sound)));buttons.append(action(e.alert?'Editar alerta':'Editar classificação',()=>editAlert(e)))}const row=[date(e.time),critical?el('span',manualCritical?'Crítico · manual':'Crítico','badge critical'):e.alert?badge(e.level):el('span','Log','badge muted'),desc,e.device,e.source_ip||'—',buttons];if(critical)row.className='event-critical-row';return row})}
function editAlert(e){const f=$('#alert-edit-form');f.elements.id.value=e.id;f.elements.title.value=e.review?.title||e.rule||'Alerta';f.elements.level.value=e.review?.level||e.level;f.elements.status.value=e.review?.status||'open';f.elements.notes.value=e.review?.notes||'';$('#alert-edit-dialog').showModal()}

function action(text,fn){if(snapshot?.role==='viewer')return el('span','');const b=el('button',text,'text-button');b.onclick=()=>run(fn);return b}
async function run(fn){try{await fn();await refresh();toast('Operação concluída')}catch(e){toast(e.message)}}
function goto(p){if(snapshot?.role==='viewer'&&!['overview','events','devices','rules','reports','network','notifications'].includes(p))p='overview';page=p;document.querySelectorAll('.page').forEach(x=>x.classList.toggle('hidden',x.id!==p));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('#breadcrumb').textContent=$(`.nav[data-page="${p}"] span`).textContent;render();if(p==='devices'&&typeof renderSSHInventory==='function')renderSSHInventory().catch(e=>toast(e.message));if(p==='network'&&typeof renderNetwork==='function')renderNetwork().catch(e=>toast(e.message));if(p==='reports'&&typeof renderReportDevices==='function')renderReportDevices();if(p==='backups'&&typeof renderBackups==='function')renderBackups().catch(e=>toast(e.message));if(p==='receivers'&&typeof renderReceivers==='function')renderReceivers().catch(e=>toast(e.message))}
document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>goto(x.dataset.page));document.querySelectorAll('[data-goto]').forEach(x=>x.onclick=()=>goto(x.dataset.goto));
function render(){if(!snapshot)return;const readOnly=snapshot.role==='viewer';document.querySelectorAll('[data-admin-only]').forEach(n=>n.hidden=readOnly);document.querySelectorAll('.nav').forEach(n=>n.hidden=readOnly&&!['overview','events','devices','rules','reports','network','notifications'].includes(n.dataset.page));if(readOnly&&!['overview','events','devices','rules','reports','network','notifications'].includes(page)){goto('overview');return}syncDashboardLayout(snapshot.preferences?.dashboard_order);if(typeof refreshHostHealth==='function')refreshHostHealth();const s=snapshot,prefs=s.preferences||{alert_min_level:1};if(s.email==='bootstrap'&&!s.local_account_ready&&!$('#local-enrollment').open)$('#local-enrollment').showModal();$('#user').textContent=s.email;const warnings=[];if(s.demo)warnings.push('DEMONSTRAÇÃO LOCAL · dados de teste somente quando solicitados · integrações externas desativadas');if(s.storage_error)warnings.push('Falha no armazenamento: '+s.storage_error);if(!s.config.auto_block)warnings.push('Modo de simulação ativo. Bloqueios não são publicados para o pfSense.');$('#banner').textContent=warnings.join(' | ');$('#banner').classList.toggle('hidden',!warnings.length);$('#demo-event').classList.toggle('hidden',!s.demo);
if(s.version)$('#product-version').textContent='Multipla Siem · v'+s.version;const events=s.events||[],blocks=s.blocks||[],rules=s.rules||[],devs=s.config.devices||[];$('#metric-events').textContent=s.total.toLocaleString('pt-BR');$('#metric-alerts').textContent=s.alerts;const allSources=devs.concat(s.snmp_devices||[]);const connection=deviceConnectionSummary(allSources,s.last_seen||{},Date.now(),s.device_presence||{});$('#metric-online').textContent=connection.online;$('#metric-offline').textContent=connection.offline;$('#metric-devices').textContent=connection.online+'/'+connection.total;$('#device-status-help').textContent=connection.monitored?'Tailscale: '+connection.monitored+' dispositivos · demais: logs em 5 min':'Referência: atividade de logs nos últimos 5 minutos';refreshCriticalIPMetric();$('#analysis-state').textContent='Ativa · diagnósticos locais';$('#local-ai-dashboard').textContent=s.local_ai?.ready?'Modelo disponível':'Aguardando modelo';$('#rule-count').textContent=rules.filter(r=>r.enabled).length+' ativas';$('#response-state').textContent=s.config.auto_block?'Publicação ativa':'Simulação';$('#mail-state').textContent=s.mail_ready?'Configurado':'Pendente';$('#posture-title').textContent=s.alerts?'Investigue os alertas':s.total?'Coleta em andamento':'Aguardando dados';$('#posture-text').textContent=s.alerts?'Revise os alertas recentes e as respostas propostas.':'O status indica coleta e configuração; não garante ausência de ameaças.';
if(page==='overview'){renderDashboardResources(s);updateDashboardDistribution();renderDeviceActivity(s);renderCompactAlerts((s.critical_events||events.filter(isCriticalEvent)).concat(events.filter(e=>e.alert&&!isCriticalEvent(e)&&e.level>=prefs.alert_min_level)).slice(0,8))}
if(page==='events'&&!eventsLivePaused){renderDeviceAlerts(s);table('#event-list',['HORÁRIO','NÍVEL','EVENTO','DISPOSITIVO','IP DE ORIGEM','AÇÃO'],eventRows((historyEventsData?.events||[]).filter(e=>!e.alert||e.level>=prefs.alert_min_level)))}
if(page==='devices')renderCompactDevices(s,devs,readOnly);
if(page==='rules')table('#rule-list',['REGRA','CORRELAÇÃO','NÍVEL','RESPOSTA','AÇÕES'],rules.map((r,i)=>{const desc=el('div',r.name);desc.append(el('small',r.pattern));const buttons=el('div');buttons.append(action('Editar',()=>startRecordEdit('rule',r)),action(r.enabled?'Pausar':'Ativar',()=>api('/api/rules','PUT',snapshot.rules.map((x,j)=>j===i?{...x,enabled:!x.enabled}:x))),action('Excluir',()=>api('/api/rules','PUT',snapshot.rules.filter((_,j)=>j!==i))));return[desc,`${r.threshold} em ${r.window_seconds}s · ${r.kind}`,badge(r.level),r.block?'Solicitar bloqueio':'Alertar',buttons]}));
if(page==='blocks')table('#block-list',['IP','MOTIVO','EXPIRAÇÃO','ESTADO','AÇÃO'],blocks.map(b=>[b.ip,b.reason,date(b.expires),el('span',b.mode==='published'?'Publicado':'Simulado','badge '+(b.mode==='published'?'high':'muted')),(()=>{const buttons=el('div');buttons.append(action('Editar',()=>startRecordEdit('block',b)),action('Remover',()=>api('/api/blocks/'+encodeURIComponent(b.ip),'DELETE')));return buttons})()]));
if(page==='settings'){renderLocalAI(s);if(typeof renderAccounts==='function')renderAccounts().catch(e=>toast(e.message));const f=$('#settings-form');if(!f.contains(document.activeElement)){['retention_days','block_minutes','mail_to','mail_min_level'].forEach(k=>f.elements[k].value=s.config[k]);f.elements.allowed_emails.value=(s.config.allowed_emails||[]).join('\n');f.elements.protected_cidrs.value=(s.config.protected_cidrs||[]).join('\n');f.elements.feed_allowed_cidrs.value=(s.config.feed_allowed_cidrs||[]).join('\n');f.elements.max_daily_mb.value=s.config.max_daily_mb||256;f.elements.auto_block.checked=s.config.auto_block;f.elements.auto_block.disabled=s.demo}$('#integration-status').textContent=`Google: ${s.google_ready?'configurado':'aguardando credenciais'} · Gmail: ${s.mail_ready?'credenciais presentes':'aguardando senha de app'}`;$('#callback').textContent='URI de retorno Google: '+s.config.public_url+'/auth/callback';$('#mail-result').textContent='Último envio: '+(s.mail_status||'sem tentativas');$('#feed-result').textContent='Última consulta ao feed: '+(new Date(s.feed_seen).getFullYear()>2000?date(s.feed_seen):'nenhuma consulta registrada')}
if(page==='audit')table('#audit-list',['HORÁRIO','ATOR','AÇÃO'],(s.audit||[]).slice().reverse().map(a=>[date(a.time),a.actor,a.action]));}
async function refresh(){try{snapshot=await api('/api/snapshot');observeCriticalSounds(snapshot);$('#live-status').textContent='Atualizado · '+new Date().toLocaleTimeString('pt-BR');if(!preferencesLoaded){preferencesLoaded=true;goto(snapshot.preferences?.default_page||'overview')}const seconds=snapshot.preferences?.refresh_seconds||5;if(!refreshHandle||seconds!==refreshSeconds){clearInterval(refreshHandle);refreshSeconds=seconds;refreshHandle=setInterval(refresh,seconds*1000)}if(page==='events'&&!eventsLivePaused){const query=$('#search').value;const fingerprint=query+'|'+historyTimeFilter+'|'+eventClientSelection;if(fingerprint!==historyQuery){historyQuery=fingerprint;historyOffset=0}historyEventsData=await api('/api/events/history?offset='+historyOffset+'&q='+encodeURIComponent(query)+historyTimeFilter+'&client='+encodeURIComponent(eventClientSelection));$('#history-previous').disabled=historyOffset===0;$('#history-next').disabled=!historyEventsData.more;$('#history-page').textContent=(historyTimeFilter?'Intervalo selecionado · registros ':'Últimas 24 horas · registros ')+(historyOffset+1)+'–'+(historyOffset+historyEventsData.events.length)+(historyEventsData.partial?' · leitura parcial: limite de consulta atingido':'')}render();if(page==='backups')await renderBackups();if(page==='receivers')await renderReceivers();if(page==='network')await renderNetwork();if(page==='devices')await renderSSHInventory()}catch(e){$('#live-status').textContent='Sem conexão';}}
function form(id,fn){$(id).onsubmit=e=>{e.preventDefault();run(async()=>{await fn(new FormData(e.target));if(id!=='#settings-form'&&id!=='#preferences-form')e.target.reset()})}}
form('#device-form',async f=>{const value={name:f.get('name'),ip:f.get('ip'),kind:f.get('kind'),mac:f.get('mac'),wol_target:f.get('wol_target'),client:f.get('client'),unit:f.get('unit')},items=snapshot.config.devices.slice();if(deviceEditing){const i=items.findIndex(d=>JSON.stringify(d)===JSON.stringify(deviceEditing));if(i<0)throw Error('O cadastro mudou. Cancele e abra a edição novamente.');items[i]=value}else items.push(value);await api('/api/config','PUT',{...snapshot.config,devices:items});cancelRecordEdit('device')});
form('#rule-form',async f=>{const value={id:f.get('id'),name:f.get('name'),kind:f.get('kind'),pattern:f.get('pattern'),threshold:Number(f.get('threshold')),window_seconds:Number(f.get('window_seconds')),level:Number(f.get('level')),block:f.has('block'),enabled:ruleEditing?ruleEditing.enabled:true},items=snapshot.rules.slice();if(ruleEditing){const i=items.findIndex(d=>JSON.stringify(d)===JSON.stringify(ruleEditing));if(i<0)throw Error('A regra mudou. Cancele e abra a edição novamente.');items[i]=value}else items.push(value);await api('/api/rules','PUT',items);cancelRecordEdit('rule')});
form('#block-form',async f=>{if(blockEditing)await api('/api/blocks/'+encodeURIComponent(blockEditing.ip),'PUT',{reason:f.get('reason')});else await api('/api/blocks','POST',Object.fromEntries(f));cancelRecordEdit('block')});
form('#settings-form',f=>api('/api/config','PUT',{...snapshot.config,retention_days:Number(f.get('retention_days')),block_minutes:Number(f.get('block_minutes')),mail_min_level:Number(f.get('mail_min_level')),mail_to:f.get('mail_to'),allowed_emails:f.get('allowed_emails').split('\n').map(x=>x.trim()).filter(Boolean),protected_cidrs:f.get('protected_cidrs').split('\n').map(x=>x.trim()).filter(Boolean),feed_allowed_cidrs:f.get('feed_allowed_cidrs').split('\n').map(x=>x.trim()).filter(Boolean),max_daily_mb:Number(f.get('max_daily_mb')),local_analysis:true,auto_block:f.has('auto_block')}));
$('#logout').onclick=()=>run(async()=>{await api('/auth/logout','POST');location.href='/'});$('#demo-event').onclick=()=>run(()=>api('/api/demo','POST'));$('#mail-test').onclick=()=>run(()=>api('/api/mail/test','POST'));$('#search').oninput=()=>refresh();$('#export-day').value=new Date().toISOString().slice(0,10);$('#export').onclick=()=>{location.href='/api/export?day='+$('#export-day').value};refresh();

let lastActivity=0;
for(const event of ['pointerdown','keydown'])document.addEventListener(event,()=>{if(snapshot&&Date.now()-lastActivity>60000){lastActivity=Date.now();api('/api/activity','POST').catch(()=>{})}},{passive:true});

$('#local-enrollment').addEventListener('cancel',e=>e.preventDefault());
$('#local-account-form').onsubmit=async e=>{e.preventDefault();const f=e.target;try{await api('/api/account/local','POST',{email:f.elements.email.value,password:f.elements.password.value});f.reset();location.href='/'}catch(err){$('#local-account-error').textContent=err.message}};$('#google-settings-open').onclick=()=>{$('#google-settings-form').reset();$('#google-settings-error').textContent='';$('#google-callback').textContent='Callback: '+location.origin+'/auth/callback';$('#google-configuration').showModal()};
$('#google-settings-close').onclick=()=>$('#google-configuration').close();
$('#google-settings-form').onsubmit=async e=>{e.preventDefault();const f=e.target;try{await api('/api/settings/google','POST',{client_id:f.elements.client_id.value,client_secret:f.elements.client_secret.value});f.reset();$('#google-configuration').close();toast('Google SSO configurado. Reconecte o Drive se já estava autorizado.')}catch(err){$('#google-settings-error').textContent=err.message}};
$('#rule-form').elements.kind.addEventListener('change',event=>{const restricted=['unifi','snmp','webhook'].includes(event.target.value),box=$('#rule-form').elements.block;box.disabled=restricted;if(restricted)box.checked=false});

function deviceAlertSummary(events,devices,now=Date.now()){
 const cutoff=now-30*60000,groups=new Map();
 for(const d of devices||[])if(d.name&&!groups.has(d.name))groups.set(d.name,{name:d.name,logs:0,alerts:0,critical:0,total:0,lastCritical:0});
 for(const e of events||[]){const time=Date.parse(e.time);if(!Number.isFinite(time)||time<cutoff||time>now)continue;const name=e.device||'Dispositivo não identificado';if(!groups.has(name))groups.set(name,{name,logs:0,alerts:0,critical:0,total:0,lastCritical:0});const g=groups.get(name);g.total++;if(e.alert&&Number(e.level)>=12){g.critical++;g.lastCritical=Math.max(g.lastCritical,time)}else if(e.alert)g.alerts++;else g.logs++}
 return Array.from(groups.values()).sort((a,b)=>b.critical-a.critical||b.alerts-a.alerts||b.total-a.total||a.name.localeCompare(b.name,'pt-BR'));
}
function deviceActivitySeries(events,devices,now=Date.now()){
 const minute=Math.floor(now/60000),groups=new Map();
 for(const d of devices||[])if(d.name&&!groups.has(d.name))groups.set(d.name,{name:d.name,bins:Array(30).fill(0),total:0});
 for(const e of events||[]){const t=Date.parse(e.time),index=Math.floor(t/60000)-(minute-29);if(!Number.isFinite(t)||t>now||index<0||index>29)continue;const name=e.device||'Dispositivo não identificado';if(!groups.has(name))groups.set(name,{name,bins:Array(30).fill(0),total:0});const g=groups.get(name);g.bins[index]++;g.total++}
 return Array.from(groups.values()).sort((a,b)=>b.total-a.total||a.name.localeCompare(b.name,'pt-BR'));
}
const activityColors=['#53dec1','#6baeff','#ffbc66','#c19bff','#ff8eab','#9cda6f','#57d1ec','#e4d479','#b9c6d5'];

let activityHistoryData=null,activityHistoryKey='',activityHistoryFetched=0,activityHistoryBusy=false,activityHistoryRequest=0,activitySelection='';
async function refreshActivityHistory(force=false){
 const key=new URLSearchParams({period:$('#activity-period').value,mode:$('#activity-mode').value}).toString();if(!force&&key===activityHistoryKey&&(activityHistoryBusy||Date.now()-activityHistoryFetched<60000))return;
 activityHistoryKey=key;activityHistoryBusy=true;const request=++activityHistoryRequest;$('#activity-history-status').textContent='Consultando logs…';
 try{const data=await api('/api/dashboard/activity?'+key);if(request!==activityHistoryRequest)return;activityHistoryData=data;activityHistoryFetched=Date.now();renderDeviceActivity(snapshot)}catch(error){if(request!==activityHistoryRequest)return;activityHistoryData=null;activityHistoryFetched=Date.now();$('#chart').replaceChildren(el('p','Não foi possível consultar a atividade dos logs.','empty'));$('#activity-history-status').textContent=error.message}finally{if(request===activityHistoryRequest)activityHistoryBusy=false}
}
function renderDeviceActivity(s){
 const expected=new URLSearchParams({period:$('#activity-period').value,mode:$('#activity-mode').value}).toString(),data=expected===activityHistoryKey?activityHistoryData:null;
 const series=data?.series||[],times=data?.times||[],select=$('#activity-device'),selected=select.value||activitySelection;
 select.replaceChildren();const all=el('option','Todos os dispositivos');all.value='';select.append(all);for(const g of series){const option=el('option',g.name);option.value=g.name;select.append(option)}select.value=series.some(g=>g.name===selected)?selected:'';select.onchange=()=>{activitySelection=select.value;renderDeviceActivity(snapshot)};
 $('#activity-period').onchange=$('#activity-mode').onchange=()=>{activityHistoryData=null;refreshActivityHistory(true);renderDeviceActivity(snapshot)};
 let visible=select.value?series.filter(g=>g.name===select.value):series.slice(0,8);
 if(!select.value&&series.length>8){const rest=series.slice(8);visible=visible.concat([{name:'Outros dispositivos ('+rest.length+')',total:rest.reduce((n,g)=>n+g.total,0),bins:times.map((_,i)=>rest.reduce((n,g)=>n+g.bins[i],0)),other:true}])}
 const box=$('#chart'),legend=$('#activity-legend');renderDeviceDonut(dashboardDistribution||deviceActivitySeries(s.events,s.config.devices));box.replaceChildren();legend.replaceChildren();
 const axis=box.parentNode.querySelector('.chart-axis');axis.replaceChildren();if(data){const period=$('#activity-period').selectedOptions[0].textContent;$('#activity-history-status').textContent='Logs/min · '+period+' · '+($('#activity-mode').value==='maximum'?'máximo por intervalo':'média por intervalo')+(data.partial?' · leitura parcial':'')+(data.missing_days?.length?' · há dias sem arquivo':'');[0,Math.floor((times.length-1)/2),times.length-1].forEach(i=>axis.append(el('span',new Date(times[i]).toLocaleString('pt-BR',$('#activity-period').value==='7d'||$('#activity-period').value==='24h'?{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}:{hour:'2-digit',minute:'2-digit'}))))}
 if(!series.length){box.append(el('div',data?'Nenhum log disponível neste período.':'Consultando atividade dos logs…','empty'));refreshActivityHistory();return}
 const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 760 230');svg.setAttribute('role','img');svg.setAttribute('aria-label','Atividade de logs por dispositivo no período selecionado');svg.setAttribute('tabindex','0');const max=Math.max(1,...visible.flatMap(g=>g.bins)),last=Math.max(1,times.length-1),x=j=>48+j*700/last,y=n=>190-n/max*168;
 const node=(tag,attrs,text)=>{const n=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;return n};
 for(let i=0;i<=4;i++){const yy=190-i*42;svg.append(node('line',{x1:48,x2:748,y1:yy,y2:yy,stroke:'#293845'}),node('text',{x:2,y:yy+4,fill:'#8498ac','font-size':11},(max*i/4).toFixed(max<10?1:0)))}
 for(let i=0;i<=6;i++)svg.append(node('line',{x1:48+i*700/6,x2:48+i*700/6,y1:22,y2:190,stroke:'#263642','stroke-opacity':.65}));
 visible.forEach((g,i)=>{const color=activityColors[i],item=el('button',undefined,'activity-legend-item');item.type='button';const dot=el('i');dot.style.background=color;item.append(dot,el('span',g.name+' · '+g.total.toLocaleString('pt-BR')));item.disabled=!!g.other;item.onclick=()=>{select.value=select.value===g.name?'':g.name;activitySelection=select.value;renderDeviceActivity(snapshot)};legend.append(item);
 const path=g.bins.map((n,j)=>(j?'L':'M')+x(j).toFixed(2)+','+y(n).toFixed(2)).join(' ');svg.append(node('path',{d:path+' L748,190 L48,190 Z',fill:color,'fill-opacity':.18,stroke:'none'}),node('path',{d:path,fill:'none',stroke:color,'stroke-width':2,'stroke-opacity':.85,'stroke-linejoin':'round'}));
 });
 const cursor=node('line',{x1:48,x2:48,y1:22,y2:190,stroke:'#b9cbd9','stroke-dasharray':'3 3',visibility:'hidden'}),feedback=el('p','Logs recebidos · toque ou passe sobre o gráfico para consultar.','activity-values');feedback.setAttribute('aria-live','polite');svg.append(cursor);let focusIndex=last;
 const inspect=i=>{focusIndex=Math.max(0,Math.min(last,i));cursor.setAttribute('x1',x(focusIndex));cursor.setAttribute('x2',x(focusIndex));cursor.setAttribute('visibility','visible');feedback.textContent=date(times[focusIndex])+' · '+visible.map(g=>g.name+': '+Number(g.bins[focusIndex]).toFixed(1)+' logs/min').join(' | ')};
 svg.onpointermove=e=>{const bounds=svg.getBoundingClientRect();inspect(Math.round(((e.clientX-bounds.left)/bounds.width*760-48)/700*last))};svg.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();inspect(focusIndex+(e.key==='ArrowRight'?1:-1))}};svg.onfocus=()=>inspect(focusIndex);box.append(svg,feedback);refreshActivityHistory();
}

function startRecordEdit(type,value){
 const f=$('#'+type+'-form');f.reset();const record=JSON.parse(JSON.stringify(value));if(type==='device')deviceEditing=record;if(type==='rule')ruleEditing=record;if(type==='block')blockEditing=record;
 for(const input of f.elements){if(!input.name||!(input.name in value))continue;if(input.type==='checkbox')input.checked=!!value[input.name];else input.value=value[input.name]}
 if(type==='rule'){ruleSample='';$('#rule-event-context').hidden=true;$('#rule-test-result').textContent='';f.elements.id.readOnly=true;f.elements.kind.dispatchEvent(new Event('change'))}if(type==='block')f.elements.ip.readOnly=true;
 $('#'+type+'-form-title').textContent=type==='device'?'Editar dispositivo':type==='rule'?'Editar regra':'Editar motivo da resposta';f.querySelector('button[type="submit"]').textContent='Salvar alterações';$('#'+type+'-cancel').hidden=false;f.scrollIntoView({behavior:'smooth',block:'center'});f.elements[type==='block'?'reason':'name'].focus();
}
function cancelRecordEdit(type){if(type==='device')deviceEditing=null;if(type==='rule')ruleEditing=null;if(type==='block')blockEditing=null;const f=$('#'+type+'-form');f.reset();if(type==='rule'){ruleSample='';$('#rule-event-context').hidden=true;$('#rule-event-preview').textContent='';$('#rule-test-result').textContent='';f.elements.id.readOnly=false;f.elements.kind.dispatchEvent(new Event('change'))}if(type==='block')f.elements.ip.readOnly=false;$('#'+type+'-form-title').textContent=type==='device'?'Adicionar dispositivo':type==='rule'?'Criar regra':'Adicionar IP à resposta';f.querySelector('button[type="submit"]').textContent=type==='device'?'Adicionar':type==='rule'?'Criar regra':'Adicionar com expiração';$('#'+type+'-cancel').hidden=true}
for(const type of ['device','rule','block'])$('#'+type+'-cancel').onclick=()=>cancelRecordEdit(type);

let ruleSample='';
const ruleExamples={
 ssh:{name:'Tentativas repetidas de acesso SSH',kind:'any',pattern:'(?i)(failed password|authentication failure|authentication failed|invalid user)',threshold:5,window_seconds:120,level:10},
 firewall:{name:'Bloqueios repetidos no pfSense',kind:'pfsense',pattern:'filterlog.*,(block|reject),',threshold:30,window_seconds:60,level:8},
 disk:{name:'Falha de disco ou armazenamento',kind:'proxmox',pattern:'(?i)(I/O error|ata.*error|nvme.*(error|failed)|filesystem.*error|smart.*failed)',threshold:1,window_seconds:60,level:12},
 hardware:{name:'Temperatura ou falha de hardware',kind:'any',pattern:'(?i)(critical temperature|thermal.*critical|machine check|hardware error|uncorrectable.*error)',threshold:1,window_seconds:60,level:13}
};
function draftRule(values){cancelRecordEdit('rule');ruleSample='';goto('rules');const f=$('#rule-form');for(const [key,value] of Object.entries(values))if(f.elements[key])f.elements[key].value=value;f.elements.id.value='regra-'+Date.now().toString(36);f.elements.block.checked=false;f.elements.kind.dispatchEvent(new Event('change'));f.scrollIntoView({behavior:'smooth',block:'center'});f.elements.name.focus();toast('Rascunho preenchido. Revise e clique em Criar regra para salvar.');}
$('#rule-example-use').onclick=()=>{const example=ruleExamples[$('#rule-example').value];if(!example){toast('Selecione um exemplo');return}draftRule(example)};
function literalRulePattern(message){return String(message).slice(0,120).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function draftRuleFromEvent(event){
 const message=event.message||'',known=/failed password|authentication fail|invalid user/i.test(message)?ruleExamples.ssh:/filterlog.*,(block|reject),/.test(message)?ruleExamples.firewall:/I\/O error|filesystem.*error|smart.*failed/i.test(message)?ruleExamples.disk:null;
 const kind=['pfsense','proxmox','generic','unifi','snmp','webhook'].includes(event.kind)?event.kind:'any';
 draftRule({...known,name:'Detectar evento · '+(event.device||'dispositivo').slice(0,70),kind,pattern:known?known.pattern:literalRulePattern(message),threshold:known?known.threshold:1,window_seconds:known?known.window_seconds:60,level:known?known.level:10});ruleSample=message;$('#rule-event-context').hidden=false;$('#rule-event-preview').textContent=message;$('#rule-test-result').textContent=known?'Padrão sugerido a partir da categoria do evento.':'Padrão literal inicial: ajuste o trecho estável para detectar eventos semelhantes.';
}
$('#rule-test').onclick=async()=>{try{const f=$('#rule-form'),result=await api('/api/rules/test','POST',{pattern:f.elements.pattern.value,kind:f.elements.kind.value,message:ruleSample});$('#rule-test-result').textContent=(ruleSample?(result.sample_match?'Corresponde ao evento selecionado. ':'Não corresponde ao evento selecionado. '):'')+result.matches+' registros correspondentes entre '+result.checked+' registros recentes. Nenhuma regra foi salva.'}catch(error){$('#rule-test-result').textContent=error.message}};

function deviceHasRecentEvent(lastSeen,now=Date.now()){const time=new Date(lastSeen).getTime();return Number.isFinite(time)&&time<=now&&now-time<300000;}
function deviceConnectionSummary(devices,lastSeen,now=Date.now(),presence={}){const unique=new Map();for(const device of devices)unique.set(device.name,device);const total=unique.size;let online=0,monitored=0;for(const device of unique.values()){const tracked=Object.hasOwn(presence,device.ip);if(tracked)monitored++;if(tracked?presence[device.ip]:deviceHasRecentEvent(lastSeen[device.name],now))online++;}return{online,offline:total-online,total,monitored};}

function renderLocalAI(s){const state=s.local_ai||{};$('#internet-analysis').checked=!!state.internet;$('#internet-analysis-status').textContent=state.internet?(state.research_ready?'Pesquisa externa habilitada.':'Pesquisa habilitada, aguardando chave da API de busca.'):'Pesquisa externa desativada; análise local mantida.';$('#local-ai-status').textContent=state.status||'Verificando modelo local';$('#local-ai-queue').textContent='Aguardando IA generativa: '+(state.pending||0)+' · fila cheia: '+(state.skipped||0)+'. Todo crítico mantém o diagnóstico da base local.';const select=$('#local-ai-model');if(document.activeElement!==select){select.replaceChildren();for(const name of state.models||[]){const option=el('option',name);option.value=name;select.append(option)}select.value=state.model||'';select.disabled=!state.models?.length}$('#local-ai-form button').disabled=!state.models?.length}
form('#local-ai-form',f=>api('/api/analysis/model','PUT',{model:f.get('model')}));
form('#alert-edit-form',async f=>{await api('/api/alerts/'+encodeURIComponent(f.get('id')),'PUT',{title:f.get('title'),level:Number(f.get('level')),status:f.get('status'),notes:f.get('notes')});$('#alert-edit-dialog').close()});$('#alert-edit-cancel').onclick=()=>$('#alert-edit-dialog').close();

$('#internet-analysis').onchange=()=>run(async()=>{await api('/api/analysis/internet','PUT',{enabled:$('#internet-analysis').checked});await refresh()});

$('#history-previous').onclick=()=>{historyOffset=Math.max(0,historyOffset-100);refresh()};
$('#history-next').onclick=()=>{historyOffset+=100;refresh()};

function setEventsLivePaused(paused){eventsLivePaused=paused;$('#events-live-toggle').textContent=paused?'Retomar atualização':'Pausar atualização';$('#events-live-toggle').setAttribute('aria-pressed',String(paused));$('#events-live-state').textContent=paused?'Atualização pausada · coleta e análise continuam no servidor.':'Atualização ao vivo ativa';$('#history-previous').disabled=paused||historyOffset===0;$('#history-next').disabled=paused||!historyEventsData?.more;if(!paused)refresh()}
$('#events-live-toggle').onclick=()=>setEventsLivePaused(!eventsLivePaused);

$('#history-apply').onclick=()=>{
 try{const from=$('#history-from').value,to=$('#history-to').value;const params=new URLSearchParams();if(from)params.set('from',new Date(from).toISOString());if(to)params.set('to',new Date(to).toISOString());const start=from?new Date(from).getTime():to?new Date(to).getTime()-86400000:Date.now()-86400000,end=to?new Date(to).getTime():Date.now();if(start>=end||end>Date.now()||end-start>31*86400000)throw Error('Selecione um intervalo passado de até 31 dias, com início anterior ao fim.');historyTimeFilter=params.toString()?'&'+params.toString():'';historyOffset=0;setEventsLivePaused(false)}catch(error){toast(error.message)}
};
$('#history-clear').onclick=()=>{$('#search').value='';$('#history-from').value='';$('#history-to').value='';historyTimeFilter='';historyOffset=0;setEventsLivePaused(false)};

function eventAssignedClient(e,index){return Object.prototype.hasOwnProperty.call(index,'name:'+e.device)?index['name:'+e.device]:(index['ip:'+e.sender_ip]||'')}
function selectEventClient(value){eventClientSelection=value;$('#event-client').value=value;historyOffset=0;historyQuery='';setEventsLivePaused(false)}
$('#event-client').onchange=e=>selectEventClient(e.target.value);
$('#event-all-clients').onclick=()=>selectEventClient('');
function renderDeviceAlerts(s){
 const index=s.event_clients||{},groups=new Map(),cutoff=Date.now()-30*60000;
 for(const name of Object.values(index))if(name&&!groups.has(name))groups.set(name,{name,total:0,critical:0});
 let unassigned=false;
 for(const e of s.events||[]){const time=Date.parse(e.time);if(!Number.isFinite(time)||time<cutoff||time>Date.now())continue;const assigned=eventAssignedClient(e,index),name=assigned||'~unassigned';if(!assigned)unassigned=true;if(!groups.has(name))groups.set(name,{name,total:0,critical:0});const g=groups.get(name);g.total++;if(isCriticalEvent(e))g.critical++;}
 const sorted=Array.from(groups.values()).sort((a,b)=>a.name==='~unassigned'?1:b.name==='~unassigned'?-1:a.name.localeCompare(b.name,'pt-BR',{sensitivity:'base'}));
 const picker=$('#event-client'),options=[['','Todos os clientes'],...sorted.map(g=>[g.name,g.name==='~unassigned'?'Sem cliente atribuído':g.name])];if(eventClientSelection&&!options.some(x=>x[0]===eventClientSelection))options.push([eventClientSelection,eventClientSelection==='~unassigned'?'Sem cliente atribuído':eventClientSelection]);
 const signature=JSON.stringify(options);if(picker.dataset.options!==signature){picker.replaceChildren(...options.map(([value,label])=>{const option=el('option',label);option.value=value;return option}));picker.dataset.options=signature}picker.value=eventClientSelection;
 $('#events-focus-title').textContent='Logs · '+(eventClientSelection==='~unassigned'?'Sem cliente atribuído':eventClientSelection||'todos os clientes');
 const all=$('#event-all-clients');all.setAttribute('aria-pressed',String(!eventClientSelection));all.textContent='Todos os clientes · '+sorted.reduce((n,g)=>n+g.total,0).toLocaleString('pt-BR')+' eventos';
 const chart=$('#device-alert-chart'),scroll=chart.scrollTop,focused=chart.contains(document.activeElement)?document.activeElement.dataset.client:null;chart.replaceChildren();const max=Math.max(1,...sorted.map(g=>g.total));
 for(const g of sorted){const row=el('button',undefined,'event-client-tab secondary');row.type='button';row.dataset.client=g.name;row.setAttribute('aria-pressed',String(eventClientSelection===g.name));row.onclick=()=>selectEventClient(g.name);row.append(el('strong',g.name==='~unassigned'?'Sem cliente atribuído':g.name));const counts=el('span',undefined,'event-client-counts');counts.append(el('span',g.total.toLocaleString('pt-BR')+' eventos'),el('span',g.critical+' críticos',g.critical?'critical-text':''));const track=el('span',undefined,'event-client-track'),fill=el('span');fill.style.width=g.total/max*100+'%';track.append(fill);row.append(counts,track);chart.append(row)}
 if(!sorted.length)chart.append(el('p','Nenhum cliente cadastrado ou evento recente.'));chart.scrollTop=scroll;if(focused!==null){const button=Array.from(chart.children).find(b=>b.dataset.client===focused);button?.focus({preventScroll:true});}
}