'use strict';
let snapshot, page='overview', timer, refreshHandle, refreshSeconds=5, preferencesLoaded=false;
const $=s=>document.querySelector(s);
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function toast(text){$('#toast').textContent=text;$('#toast').classList.remove('hidden');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.add('hidden'),7000)}
async function api(path,method='GET',body){const r=await fetch(path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':snapshot?.csrf||''},body:body===undefined?undefined:JSON.stringify(body)});if(r.status===401){location.href='/';throw Error('Sessão expirada')}if(!r.ok)throw Error(await r.text());return r.json()}
function date(t){return new Date(t).toLocaleString('pt-BR')}
function badge(level){return el('span',level>=12?'Crítico · '+level:level>=10?'Alto · '+level:level>=7?'Médio · '+level:'Baixo · '+level,'badge '+(level>=10?'high':level>=7?'medium':'muted'))}
function table(target,headers,rows){const box=$(target);box.replaceChildren();if(!rows.length){box.append(el('div','Nenhum registro nesta janela.','empty'));return}const t=el('table'),head=el('thead'),tr=el('tr');headers.forEach(h=>tr.append(el('th',h)));head.append(tr);t.append(head);const b=el('tbody');rows.forEach(row=>{const tr=el('tr');row.forEach(x=>{const td=el('td');if(x instanceof Node)td.append(x);else td.textContent=x;tr.append(td)});b.append(tr)});t.append(b);box.append(t)}
function eventRows(evs){return evs.map(e=>{const desc=el('div',e.alert?e.rule:e.message);desc.append(el('small',(e.detector?e.detector+' · ':'')+(e.protocol?e.protocol+' · ':'')+(e.alert?e.message:e.kind)));if(e.cef)desc.append(el('small',e.cef.vendor+' / '+e.cef.product+' · '+e.cef.name+' · severidade CEF '+e.cef.severity+(e.cef.category?' · '+e.cef.category:'')));desc.className='message';return [date(e.time),e.alert?badge(e.level):el('span','Log','badge muted'),desc,e.device,e.source_ip||'—']})}
function action(text,fn){const b=el('button',text,'text-button');b.onclick=()=>run(fn);return b}
async function run(fn){try{await fn();await refresh();toast('Operação concluída')}catch(e){toast(e.message)}}
function goto(p){page=p;document.querySelectorAll('.page').forEach(x=>x.classList.toggle('hidden',x.id!==p));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('#breadcrumb').textContent=$(`.nav[data-page="${p}"] span`).textContent;render();if(p==='backups'&&typeof renderBackups==='function')renderBackups().catch(e=>toast(e.message));if(p==='receivers'&&typeof renderReceivers==='function')renderReceivers().catch(e=>toast(e.message))}
document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>goto(x.dataset.page));document.querySelectorAll('[data-goto]').forEach(x=>x.onclick=()=>goto(x.dataset.goto));
function render(){if(!snapshot)return;const s=snapshot;if(s.email==='bootstrap'&&!s.local_account_ready&&!$('#local-enrollment').open)$('#local-enrollment').showModal();$('#user').textContent=s.email;const warnings=[];if(s.demo)warnings.push('DEMONSTRAÇÃO LOCAL · dados de teste somente quando solicitados · integrações externas desativadas');if(s.storage_error)warnings.push('Falha no armazenamento: '+s.storage_error);if(!s.config.auto_block)warnings.push('Modo de simulação ativo. Bloqueios não são publicados para o pfSense.');$('#banner').textContent=warnings.join(' | ');$('#banner').classList.toggle('hidden',!warnings.length);$('#demo-event').classList.toggle('hidden',!s.demo);
const events=s.events||[],blocks=s.blocks||[],rules=s.rules||[],devs=s.config.devices||[];$('#metric-events').textContent=s.total.toLocaleString('pt-BR');$('#metric-alerts').textContent=s.alerts;const allSources=devs.concat(s.snmp_devices||[]);$('#metric-devices').textContent=allSources.filter(d=>s.last_seen[d.name]&&Date.now()-new Date(s.last_seen[d.name])<300000).length+'/'+allSources.length;$('#metric-blocks').textContent=blocks.length;$('#mode-label').textContent=s.config.auto_block?'Lista publicada para o pfSense':'Modo de simulação';$('#rule-count').textContent=rules.filter(r=>r.enabled).length+' ativas';$('#response-state').textContent=s.config.auto_block?'Publicação ativa':'Simulação';$('#mail-state').textContent=s.mail_ready?'Configurado':'Pendente';$('#posture-title').textContent=s.alerts?'Investigue os alertas':s.total?'Coleta em andamento':'Aguardando dados';$('#posture-text').textContent=s.alerts?'Revise os alertas recentes e as respostas propostas.':'O status indica coleta e configuração; não garante ausência de ameaças.';
if(page==='overview'){const bins=s.bins||Array(30).fill(0);const max=Math.max(1,...bins);$('#chart').replaceChildren(...bins.map((n,i)=>{const b=el('div',undefined,'bar');b.style.height=(n/max*95+1)+'%';b.title=`${29-i} min atrás: ${n} eventos (janela em memória)`;return b}));table('#recent-alerts',['HORÁRIO','NÍVEL','ALERTA','DISPOSITIVO','IP DE ORIGEM'],eventRows(events.filter(e=>e.alert&&e.level>=prefs.alert_min_level).slice(0,8)))}
if(page==='events')table('#event-list',['HORÁRIO','NÍVEL','EVENTO','DISPOSITIVO','IP DE ORIGEM'],eventRows(events.filter(e=>!e.alert||e.level>=prefs.alert_min_level)));
if(page==='devices'){const grid=$('#device-list');grid.replaceChildren();devs.forEach((d,i)=>{const card=el('article',undefined,'device-card');const seen=s.last_seen[d.name];card.append(el('span',seen&&Date.now()-new Date(seen)<300000?'Recebendo logs':'Aguardando logs','badge'),el('h2',d.name),el('p',d.kind+' · '+d.ip),el('p',seen?'Último evento: '+date(seen):'Nenhum evento recebido'),action('Remover',()=>api('/api/config','PUT',{...snapshot.config,devices:snapshot.config.devices.filter((_,j)=>j!==i)})));grid.append(card)})}
if(page==='rules')table('#rule-list',['REGRA','CORRELAÇÃO','NÍVEL','RESPOSTA','AÇÕES'],rules.map((r,i)=>{const desc=el('div',r.name);desc.append(el('small',r.pattern));const buttons=el('div');buttons.append(action(r.enabled?'Pausar':'Ativar',()=>api('/api/rules','PUT',snapshot.rules.map((x,j)=>j===i?{...x,enabled:!x.enabled}:x))),action('Excluir',()=>api('/api/rules','PUT',snapshot.rules.filter((_,j)=>j!==i))));return[desc,`${r.threshold} em ${r.window_seconds}s · ${r.kind}`,badge(r.level),r.block?'Solicitar bloqueio':'Alertar',buttons]}));
if(page==='blocks')table('#block-list',['IP','MOTIVO','EXPIRAÇÃO','ESTADO','AÇÃO'],blocks.map(b=>[b.ip,b.reason,date(b.expires),el('span',b.mode==='published'?'Publicado':'Simulado','badge '+(b.mode==='published'?'high':'muted')),action('Remover',()=>api('/api/blocks/'+encodeURIComponent(b.ip),'DELETE'))]));
if(page==='settings'){const f=$('#settings-form');if(!f.contains(document.activeElement)){['retention_days','block_minutes','mail_to','mail_min_level'].forEach(k=>f.elements[k].value=s.config[k]);f.elements.allowed_emails.value=(s.config.allowed_emails||[]).join('\n');f.elements.protected_cidrs.value=(s.config.protected_cidrs||[]).join('\n');f.elements.feed_allowed_cidrs.value=(s.config.feed_allowed_cidrs||[]).join('\n');f.elements.max_daily_mb.value=s.config.max_daily_mb||256;f.elements.local_analysis.checked=s.config.local_analysis;f.elements.auto_block.checked=s.config.auto_block;f.elements.auto_block.disabled=s.demo}$('#integration-status').textContent=`Google: ${s.google_ready?'configurado':'aguardando credenciais'} · Gmail: ${s.mail_ready?'credenciais presentes':'aguardando senha de app'}`;$('#callback').textContent='URI de retorno Google: '+s.config.public_url+'/auth/callback';$('#mail-result').textContent='Último envio: '+(s.mail_status||'sem tentativas');$('#feed-result').textContent='Última consulta ao feed: '+(new Date(s.feed_seen).getFullYear()>2000?date(s.feed_seen):'nenhuma consulta registrada')}
if(page==='audit')table('#audit-list',['HORÁRIO','ATOR','AÇÃO'],(s.audit||[]).slice().reverse().map(a=>[date(a.time),a.actor,a.action]));}
async function refresh(){try{snapshot=await api('/api/snapshot?q='+encodeURIComponent(page==='events'?$('#search').value:''));$('#live-status').textContent='Atualizado · '+new Date().toLocaleTimeString('pt-BR');if(!preferencesLoaded){preferencesLoaded=true;goto(snapshot.preferences?.default_page||'overview')}const seconds=snapshot.preferences?.refresh_seconds||5;if(!refreshHandle||seconds!==refreshSeconds){clearInterval(refreshHandle);refreshSeconds=seconds;refreshHandle=setInterval(refresh,seconds*1000)}render();if(page==='backups')await renderBackups();if(page==='receivers')await renderReceivers()}catch(e){$('#live-status').textContent='Sem conexão';}}
function form(id,fn){$(id).onsubmit=e=>{e.preventDefault();run(async()=>{await fn(new FormData(e.target));if(id!=='#settings-form'&&id!=='#preferences-form')e.target.reset()})}}
form('#device-form',f=>api('/api/config','PUT',{...snapshot.config,devices:[...snapshot.config.devices,{name:f.get('name'),ip:f.get('ip'),kind:f.get('kind')}]}));
form('#rule-form',f=>api('/api/rules','PUT',[...snapshot.rules,{id:f.get('id'),name:f.get('name'),kind:f.get('kind'),pattern:f.get('pattern'),threshold:Number(f.get('threshold')),window_seconds:Number(f.get('window_seconds')),level:Number(f.get('level')),block:f.has('block'),enabled:true}]));
form('#block-form',f=>api('/api/blocks','POST',Object.fromEntries(f)));
form('#settings-form',f=>api('/api/config','PUT',{...snapshot.config,retention_days:Number(f.get('retention_days')),block_minutes:Number(f.get('block_minutes')),mail_min_level:Number(f.get('mail_min_level')),mail_to:f.get('mail_to'),allowed_emails:f.get('allowed_emails').split('\n').map(x=>x.trim()).filter(Boolean),protected_cidrs:f.get('protected_cidrs').split('\n').map(x=>x.trim()).filter(Boolean),feed_allowed_cidrs:f.get('feed_allowed_cidrs').split('\n').map(x=>x.trim()).filter(Boolean),max_daily_mb:Number(f.get('max_daily_mb')),local_analysis:f.has('local_analysis'),auto_block:f.has('auto_block')}));
$('#logout').onclick=()=>run(async()=>{await api('/auth/logout','POST');location.href='/'});$('#demo-event').onclick=()=>run(()=>api('/api/demo','POST'));$('#mail-test').onclick=()=>run(()=>api('/api/mail/test','POST'));$('#search').oninput=()=>refresh();$('#export-day').value=new Date().toISOString().slice(0,10);$('#export').onclick=()=>{location.href='/api/export?day='+$('#export-day').value};refresh();

let lastActivity=0;
for(const event of ['pointerdown','keydown'])document.addEventListener(event,()=>{if(snapshot&&Date.now()-lastActivity>60000){lastActivity=Date.now();api('/api/activity','POST').catch(()=>{})}},{passive:true});

$('#local-enrollment').addEventListener('cancel',e=>e.preventDefault());
$('#local-account-form').onsubmit=async e=>{e.preventDefault();const f=e.target;try{await api('/api/account/local','POST',{email:f.elements.email.value,password:f.elements.password.value});f.reset();location.href='/'}catch(err){$('#local-account-error').textContent=err.message}};$('#google-settings-open').onclick=()=>{$('#google-callback').textContent='Callback: '+location.origin+'/auth/callback';$('#google-configuration').showModal()};
$('#google-settings-close').onclick=()=>$('#google-configuration').close();
$('#google-settings-form').onsubmit=async e=>{e.preventDefault();const f=e.target;try{await api('/api/settings/google','POST',{client_id:f.elements.client_id.value,client_secret:f.elements.client_secret.value});f.reset();$('#google-configuration').close();toast('Google SSO configurado. Reconecte o Drive se já estava autorizado.')}catch(err){$('#google-settings-error').textContent=err.message}};
$('#rule-form').elements.kind.addEventListener('change',event=>{const restricted=['unifi','snmp','webhook'].includes(event.target.value),box=$('#rule-form').elements.block;box.disabled=restricted;if(restricted)box.checked=false});
