'use strict';
let deviceEditing=null,ruleEditing=null,blockEditing=null;
let snapshot, page='overview', timer, refreshHandle, refreshSeconds=5, preferencesLoaded=false;
const $=s=>document.querySelector(s);
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function toast(text){$('#toast').textContent=text;$('#toast').classList.remove('hidden');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.add('hidden'),7000)}
async function api(path,method='GET',body){const r=await fetch(path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':snapshot?.csrf||''},body:body===undefined?undefined:JSON.stringify(body)});if(r.status===401){location.href='/';throw Error('Sessão expirada')}if(!r.ok)throw Error(await r.text());return r.json()}
function date(t){return new Date(t).toLocaleString('pt-BR')}
function badge(level){return el('span',level>=12?'Crítico · '+level:level>=10?'Alto · '+level:level>=7?'Médio · '+level:'Baixo · '+level,'badge '+(level>=10?'high':level>=7?'medium':'muted'))}
function table(target,headers,rows){const box=$(target);box.replaceChildren();if(!rows.length){box.append(el('div','Nenhum registro nesta janela.','empty'));return}const t=el('table'),head=el('thead'),tr=el('tr');headers.forEach(h=>tr.append(el('th',h)));head.append(tr);t.append(head);const b=el('tbody');rows.forEach(row=>{const tr=el('tr');row.forEach(x=>{const td=el('td');if(x instanceof Node)td.append(x);else td.textContent=x;tr.append(td)});b.append(tr)});t.append(b);box.append(t)}
function eventRows(evs){return evs.map(e=>{const desc=el('div',e.alert?e.rule:e.message);desc.append(el('small',(e.detector?e.detector+' · ':'')+(e.protocol?e.protocol+' · ':'')+(e.alert?e.message:e.kind)));if(e.cef)desc.append(el('small',e.cef.vendor+' / '+e.cef.product+' · '+e.cef.name+' · severidade CEF '+e.cef.severity+(e.cef.category?' · '+e.cef.category:'')));desc.className='message';return [date(e.time),e.alert?badge(e.level):el('span','Log','badge muted'),desc,e.device,e.source_ip||'—',action('Criar regra',()=>draftRuleFromEvent(e))]})}
function action(text,fn){const b=el('button',text,'text-button');b.onclick=()=>run(fn);return b}
async function run(fn){try{await fn();await refresh();toast('Operação concluída')}catch(e){toast(e.message)}}
function goto(p){page=p;document.querySelectorAll('.page').forEach(x=>x.classList.toggle('hidden',x.id!==p));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===p));$('#breadcrumb').textContent=$(`.nav[data-page="${p}"] span`).textContent;render();if(p==='backups'&&typeof renderBackups==='function')renderBackups().catch(e=>toast(e.message));if(p==='receivers'&&typeof renderReceivers==='function')renderReceivers().catch(e=>toast(e.message))}
document.querySelectorAll('[data-page]').forEach(x=>x.onclick=()=>goto(x.dataset.page));document.querySelectorAll('[data-goto]').forEach(x=>x.onclick=()=>goto(x.dataset.goto));
function render(){if(!snapshot)return;const s=snapshot,prefs=s.preferences||{alert_min_level:1};if(s.email==='bootstrap'&&!s.local_account_ready&&!$('#local-enrollment').open)$('#local-enrollment').showModal();$('#user').textContent=s.email;const warnings=[];if(s.demo)warnings.push('DEMONSTRAÇÃO LOCAL · dados de teste somente quando solicitados · integrações externas desativadas');if(s.storage_error)warnings.push('Falha no armazenamento: '+s.storage_error);if(!s.config.auto_block)warnings.push('Modo de simulação ativo. Bloqueios não são publicados para o pfSense.');$('#banner').textContent=warnings.join(' | ');$('#banner').classList.toggle('hidden',!warnings.length);$('#demo-event').classList.toggle('hidden',!s.demo);
const events=s.events||[],blocks=s.blocks||[],rules=s.rules||[],devs=s.config.devices||[];$('#metric-events').textContent=s.total.toLocaleString('pt-BR');$('#metric-alerts').textContent=s.alerts;const allSources=devs.concat(s.snmp_devices||[]);$('#metric-devices').textContent=allSources.filter(d=>s.last_seen[d.name]&&Date.now()-new Date(s.last_seen[d.name])<300000).length+'/'+allSources.length;$('#metric-blocks').textContent=blocks.length;$('#mode-label').textContent=s.config.auto_block?'Lista publicada para o pfSense':'Modo de simulação';$('#rule-count').textContent=rules.filter(r=>r.enabled).length+' ativas';$('#response-state').textContent=s.config.auto_block?'Publicação ativa':'Simulação';$('#mail-state').textContent=s.mail_ready?'Configurado':'Pendente';$('#posture-title').textContent=s.alerts?'Investigue os alertas':s.total?'Coleta em andamento':'Aguardando dados';$('#posture-text').textContent=s.alerts?'Revise os alertas recentes e as respostas propostas.':'O status indica coleta e configuração; não garante ausência de ameaças.';
if(page==='overview'){renderDeviceActivity(s);table('#recent-alerts',['HORÁRIO','NÍVEL','ALERTA','DISPOSITIVO','IP DE ORIGEM','AÇÃO'],eventRows(events.filter(e=>e.alert&&e.level>=prefs.alert_min_level).slice(0,8)))}
if(page==='events'){renderDeviceAlerts(s);table('#event-list',['HORÁRIO','NÍVEL','EVENTO','DISPOSITIVO','IP DE ORIGEM','AÇÃO'],eventRows(events.filter(e=>!e.alert||e.level>=prefs.alert_min_level)))}
if(page==='devices'){const grid=$('#device-list');grid.replaceChildren();devs.forEach((d,i)=>{const card=el('article',undefined,'device-card');const seen=s.last_seen[d.name];card.append(el('span',seen&&Date.now()-new Date(seen)<300000?'Recebendo logs':'Aguardando logs','badge'),el('h2',d.name),el('p',d.kind+' · '+d.ip),el('p',seen?'Último evento: '+date(seen):'Nenhum evento recebido'),action('Editar',()=>startRecordEdit('device',d)),action('Remover',()=>api('/api/config','PUT',{...snapshot.config,devices:snapshot.config.devices.filter((_,j)=>j!==i)})));grid.append(card)})}
if(page==='rules')table('#rule-list',['REGRA','CORRELAÇÃO','NÍVEL','RESPOSTA','AÇÕES'],rules.map((r,i)=>{const desc=el('div',r.name);desc.append(el('small',r.pattern));const buttons=el('div');buttons.append(action('Editar',()=>startRecordEdit('rule',r)),action(r.enabled?'Pausar':'Ativar',()=>api('/api/rules','PUT',snapshot.rules.map((x,j)=>j===i?{...x,enabled:!x.enabled}:x))),action('Excluir',()=>api('/api/rules','PUT',snapshot.rules.filter((_,j)=>j!==i))));return[desc,`${r.threshold} em ${r.window_seconds}s · ${r.kind}`,badge(r.level),r.block?'Solicitar bloqueio':'Alertar',buttons]}));
if(page==='blocks')table('#block-list',['IP','MOTIVO','EXPIRAÇÃO','ESTADO','AÇÃO'],blocks.map(b=>[b.ip,b.reason,date(b.expires),el('span',b.mode==='published'?'Publicado':'Simulado','badge '+(b.mode==='published'?'high':'muted')),(()=>{const buttons=el('div');buttons.append(action('Editar',()=>startRecordEdit('block',b)),action('Remover',()=>api('/api/blocks/'+encodeURIComponent(b.ip),'DELETE')));return buttons})()]));
if(page==='settings'){const f=$('#settings-form');if(!f.contains(document.activeElement)){['retention_days','block_minutes','mail_to','mail_min_level'].forEach(k=>f.elements[k].value=s.config[k]);f.elements.allowed_emails.value=(s.config.allowed_emails||[]).join('\n');f.elements.protected_cidrs.value=(s.config.protected_cidrs||[]).join('\n');f.elements.feed_allowed_cidrs.value=(s.config.feed_allowed_cidrs||[]).join('\n');f.elements.max_daily_mb.value=s.config.max_daily_mb||256;f.elements.local_analysis.checked=s.config.local_analysis;f.elements.auto_block.checked=s.config.auto_block;f.elements.auto_block.disabled=s.demo}$('#integration-status').textContent=`Google: ${s.google_ready?'configurado':'aguardando credenciais'} · Gmail: ${s.mail_ready?'credenciais presentes':'aguardando senha de app'}`;$('#callback').textContent='URI de retorno Google: '+s.config.public_url+'/auth/callback';$('#mail-result').textContent='Último envio: '+(s.mail_status||'sem tentativas');$('#feed-result').textContent='Última consulta ao feed: '+(new Date(s.feed_seen).getFullYear()>2000?date(s.feed_seen):'nenhuma consulta registrada')}
if(page==='audit')table('#audit-list',['HORÁRIO','ATOR','AÇÃO'],(s.audit||[]).slice().reverse().map(a=>[date(a.time),a.actor,a.action]));}
async function refresh(){try{snapshot=await api('/api/snapshot?q='+encodeURIComponent(page==='events'?$('#search').value:''));$('#live-status').textContent='Atualizado · '+new Date().toLocaleTimeString('pt-BR');if(!preferencesLoaded){preferencesLoaded=true;goto(snapshot.preferences?.default_page||'overview')}const seconds=snapshot.preferences?.refresh_seconds||5;if(!refreshHandle||seconds!==refreshSeconds){clearInterval(refreshHandle);refreshSeconds=seconds;refreshHandle=setInterval(refresh,seconds*1000)}render();if(page==='backups')await renderBackups();if(page==='receivers')await renderReceivers()}catch(e){$('#live-status').textContent='Sem conexão';}}
function form(id,fn){$(id).onsubmit=e=>{e.preventDefault();run(async()=>{await fn(new FormData(e.target));if(id!=='#settings-form'&&id!=='#preferences-form')e.target.reset()})}}
form('#device-form',async f=>{const value={name:f.get('name'),ip:f.get('ip'),kind:f.get('kind')},items=snapshot.config.devices.slice();if(deviceEditing){const i=items.findIndex(d=>JSON.stringify(d)===JSON.stringify(deviceEditing));if(i<0)throw Error('O cadastro mudou. Cancele e abra a edição novamente.');items[i]=value}else items.push(value);await api('/api/config','PUT',{...snapshot.config,devices:items});cancelRecordEdit('device')});
form('#rule-form',async f=>{const value={id:f.get('id'),name:f.get('name'),kind:f.get('kind'),pattern:f.get('pattern'),threshold:Number(f.get('threshold')),window_seconds:Number(f.get('window_seconds')),level:Number(f.get('level')),block:f.has('block'),enabled:ruleEditing?ruleEditing.enabled:true},items=snapshot.rules.slice();if(ruleEditing){const i=items.findIndex(d=>JSON.stringify(d)===JSON.stringify(ruleEditing));if(i<0)throw Error('A regra mudou. Cancele e abra a edição novamente.');items[i]=value}else items.push(value);await api('/api/rules','PUT',items);cancelRecordEdit('rule')});
form('#block-form',async f=>{if(blockEditing)await api('/api/blocks/'+encodeURIComponent(blockEditing.ip),'PUT',{reason:f.get('reason')});else await api('/api/blocks','POST',Object.fromEntries(f));cancelRecordEdit('block')});
form('#settings-form',f=>api('/api/config','PUT',{...snapshot.config,retention_days:Number(f.get('retention_days')),block_minutes:Number(f.get('block_minutes')),mail_min_level:Number(f.get('mail_min_level')),mail_to:f.get('mail_to'),allowed_emails:f.get('allowed_emails').split('\n').map(x=>x.trim()).filter(Boolean),protected_cidrs:f.get('protected_cidrs').split('\n').map(x=>x.trim()).filter(Boolean),feed_allowed_cidrs:f.get('feed_allowed_cidrs').split('\n').map(x=>x.trim()).filter(Boolean),max_daily_mb:Number(f.get('max_daily_mb')),local_analysis:f.has('local_analysis'),auto_block:f.has('auto_block')}));
$('#logout').onclick=()=>run(async()=>{await api('/auth/logout','POST');location.href='/'});$('#demo-event').onclick=()=>run(()=>api('/api/demo','POST'));$('#mail-test').onclick=()=>run(()=>api('/api/mail/test','POST'));$('#search').oninput=()=>refresh();$('#export-day').value=new Date().toISOString().slice(0,10);$('#export').onclick=()=>{location.href='/api/export?day='+$('#export-day').value};refresh();

let lastActivity=0;
for(const event of ['pointerdown','keydown'])document.addEventListener(event,()=>{if(snapshot&&Date.now()-lastActivity>60000){lastActivity=Date.now();api('/api/activity','POST').catch(()=>{})}},{passive:true});

$('#local-enrollment').addEventListener('cancel',e=>e.preventDefault());
$('#local-account-form').onsubmit=async e=>{e.preventDefault();const f=e.target;try{await api('/api/account/local','POST',{email:f.elements.email.value,password:f.elements.password.value});f.reset();location.href='/'}catch(err){$('#local-account-error').textContent=err.message}};$('#google-settings-open').onclick=()=>{$('#google-settings-form').reset();$('#google-settings-error').textContent='';$('#google-callback').textContent='Callback: '+location.origin+'/auth/callback';$('#google-configuration').showModal()};
$('#google-settings-close').onclick=()=>$('#google-configuration').close();
$('#google-settings-form').onsubmit=async e=>{e.preventDefault();const f=e.target;try{await api('/api/settings/google','POST',{client_id:f.elements.client_id.value,client_secret:f.elements.client_secret.value});f.reset();$('#google-configuration').close();toast('Google SSO configurado. Reconecte o Drive se já estava autorizado.')}catch(err){$('#google-settings-error').textContent=err.message}};
$('#rule-form').elements.kind.addEventListener('change',event=>{const restricted=['unifi','snmp','webhook'].includes(event.target.value),box=$('#rule-form').elements.block;box.disabled=restricted;if(restricted)box.checked=false});

function deviceAlertSummary(events,devices,now=Date.now()){
 const cutoff=now-30*60000,groups=new Map();
 for(const d of devices||[])if(d.name&&!groups.has(d.name))groups.set(d.name,{name:d.name,logs:0,alerts:0,critical:0,total:0,lastCritical:0});
 for(const e of events||[]){const time=Date.parse(e.time);if(!Number.isFinite(time)||time<cutoff||time>now)continue;const name=e.device||'Dispositivo não identificado';if(!groups.has(name))groups.set(name,{name,logs:0,alerts:0,critical:0,total:0,lastCritical:0});const g=groups.get(name);g.total++;if(e.alert&&Number(e.level)>=12){g.critical++;g.lastCritical=Math.max(g.lastCritical,time)}else if(e.alert)g.alerts++;else g.logs++}
 return Array.from(groups.values()).sort((a,b)=>b.critical-a.critical||b.alerts-a.alerts||b.total-a.total||a.name.localeCompare(b.name,'pt-BR'));
}
function renderDeviceAlerts(s){
 const groups=deviceAlertSummary(s.events,(s.config.devices||[]).concat((s.snmp_devices||[]).map(d=>({...d,name:'SNMP · '+d.name}))));
 $('#device-critical-count').textContent=groups.filter(g=>g.critical>0).length;$('#device-critical-total').textContent=groups.reduce((n,g)=>n+g.critical,0).toLocaleString('pt-BR');$('#device-window-total').textContent=groups.reduce((n,g)=>n+g.total,0).toLocaleString('pt-BR');$('#device-alert-refresh').textContent='Atualização a cada '+refreshSeconds+'s';
 $('#device-alert-window').textContent='Últimos 30 minutos · até 2.000 registros recentes'+($('#search').value.trim()?' · busca aplicada':'')+'.';
 const chart=$('#device-alert-chart');chart.replaceChildren();const max=Math.max(1,...groups.map(g=>g.total));
 if(!groups.length){chart.append(el('div','Cadastre dispositivos para acompanhar os eventos e alertas.','empty'));return}
 for(const g of groups){const row=el('button',undefined,'device-chart-row'+(g.critical?' has-critical':''));row.type='button';row.setAttribute('aria-label',`${g.name}: ${g.total} eventos, ${g.critical} críticos. Filtrar eventos deste dispositivo`);row.onclick=()=>{$('#search').value=g.name;refresh()};
 const label=el('div',undefined,'device-chart-label');label.append(el('strong',g.name),el('small',g.critical?'CRÍTICO · último às '+new Date(g.lastCritical).toLocaleTimeString('pt-BR'):g.total?'Sem críticos na janela':'Sem eventos na janela'));
 const track=el('div',undefined,'device-chart-track');for(const [field,cls,title] of [['logs','logs','Logs'],['alerts','alerts','Alertas'],['critical','critical','Críticos']]){if(!g[field])continue;const segment=el('span',undefined,'device-chart-segment '+cls);segment.style.width=(g[field]/max*100)+'%';segment.title=title+': '+g[field];track.append(segment)}
 const counts=el('div',undefined,'device-chart-counts');counts.append(el('strong',g.total.toLocaleString('pt-BR')),el('small',g.critical+' críticos'));row.append(label,track,counts);chart.append(row)}
}

function deviceActivitySeries(events,devices,now=Date.now()){
 const minute=Math.floor(now/60000),groups=new Map();
 for(const d of devices||[])if(d.name&&!groups.has(d.name))groups.set(d.name,{name:d.name,bins:Array(30).fill(0),total:0});
 for(const e of events||[]){const t=Date.parse(e.time),index=Math.floor(t/60000)-(minute-29);if(!Number.isFinite(t)||t>now||index<0||index>29)continue;const name=e.device||'Dispositivo não identificado';if(!groups.has(name))groups.set(name,{name,bins:Array(30).fill(0),total:0});const g=groups.get(name);g.bins[index]++;g.total++}
 return Array.from(groups.values()).sort((a,b)=>b.total-a.total||a.name.localeCompare(b.name,'pt-BR'));
}
const activityColors=['#53dec1','#6baeff','#ffbc66','#c19bff','#ff8eab','#9cda6f','#57d1ec','#e4d479','#b9c6d5'];
function renderDeviceActivity(s){
 const series=deviceActivitySeries(s.events,(s.config.devices||[]).concat((s.snmp_devices||[]).map(d=>({...d,name:'SNMP · '+d.name}))));const select=$('#activity-device'),selected=select.value;
 select.replaceChildren();const all=el('option','Todos os dispositivos');all.value='';select.append(all);for(const g of series){const option=el('option',g.name);option.value=g.name;select.append(option)}select.value=series.some(g=>g.name===selected)?selected:'';select.onchange=()=>renderDeviceActivity(snapshot);
 let visible=select.value?series.filter(g=>g.name===select.value):series.slice(0,8);
 if(!select.value&&series.length>8){const rest=series.slice(8);visible=visible.concat([{name:'Outros dispositivos ('+rest.length+')',total:rest.reduce((n,g)=>n+g.total,0),bins:Array.from({length:30},(_,i)=>rest.reduce((n,g)=>n+g.bins[i],0)),other:true}])}
 const box=$('#chart'),legend=$('#activity-legend');box.replaceChildren();legend.replaceChildren();if(!series.length){box.append(el('div','Cadastre dispositivos para acompanhar sua atividade.','empty'));return}
 const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 760 210');svg.setAttribute('role','img');svg.setAttribute('aria-label','Atividade por dispositivo nos últimos 30 minutos');const max=Math.max(1,...visible.flatMap(g=>g.bins));
 for(let i=0;i<=4;i++){const y=190-i*42,line=document.createElementNS(ns,'line');line.setAttribute('x1','36');line.setAttribute('x2','750');line.setAttribute('y1',y);line.setAttribute('y2',y);line.setAttribute('stroke','#293845');svg.append(line);const text=document.createElementNS(ns,'text');text.setAttribute('x','2');text.setAttribute('y',y+4);text.setAttribute('fill','#8498ac');text.setAttribute('font-size','11');text.textContent=Math.round(max*i/4);svg.append(text)}
 visible.forEach((g,i)=>{const color=activityColors[i],item=el('button',undefined,'activity-legend-item');item.type='button';const key=el('i');key.style.background=color;item.append(key,el('span',g.name+' · '+g.total));item.disabled=!!g.other;item.onclick=()=>{select.value=select.value===g.name?'':g.name;renderDeviceActivity(snapshot)};legend.append(item);
 const line=document.createElementNS(ns,'polyline');line.setAttribute('points',g.bins.map((n,j)=>(36+j*714/29)+','+(190-n/max*168)).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke',color);line.setAttribute('stroke-width','2.5');line.setAttribute('stroke-linejoin','round');const title=document.createElementNS(ns,'title');title.textContent=g.name+': '+g.total+' registros';line.append(title);svg.append(line);
 g.bins.forEach((n,j)=>{if(!n)return;const point=document.createElementNS(ns,'circle');point.setAttribute('cx',36+j*714/29);point.setAttribute('cy',190-n/max*168);point.setAttribute('r','3');point.setAttribute('fill',color);const title=document.createElementNS(ns,'title');title.textContent=g.name+' · '+(29-j)+' min atrás: '+n+' registros';point.append(title);svg.append(point)})});box.append(svg);
}

function startRecordEdit(type,value){
 const f=$('#'+type+'-form');f.reset();const record=JSON.parse(JSON.stringify(value));if(type==='device')deviceEditing=record;if(type==='rule')ruleEditing=record;if(type==='block')blockEditing=record;
 for(const input of f.elements){if(!input.name||!(input.name in value))continue;if(input.type==='checkbox')input.checked=!!value[input.name];else input.value=value[input.name]}
 if(type==='rule'){ruleSample='';$('#rule-event-context').hidden=true;$('#rule-test-result').textContent='';f.elements.id.readOnly=true;f.elements.kind.dispatchEvent(new Event('change'))}if(type==='block')f.elements.ip.readOnly=true;
 $('#'+type+'-form-title').textContent=type==='device'?'Editar dispositivo':type==='rule'?'Editar regra':'Editar motivo da resposta';f.querySelector('button[type="submit"]').textContent='Salvar alterações';$('#'+type+'-cancel').hidden=false;f.scrollIntoView({behavior:'smooth',block:'center'});f.elements[type==='block'?'reason':'name'].focus();
}
function cancelRecordEdit(type){if(type==='device')deviceEditing=null;if(type==='rule')ruleEditing=null;if(type==='block')blockEditing=null;const f=$('#'+type+'-form');f.reset();if(type==='rule'){ruleSample='';$('#rule-event-context').hidden=true;$('#rule-event-preview').textContent='';$('#rule-test-result').textContent='';f.elements.id.readOnly=false;f.elements.kind.dispatchEvent(new Event('change'))}if(type==='block')f.elements.ip.readOnly=false;$('#'+type+'-form-title').textContent=type==='device'?'Adicionar dispositivo':type==='rule'?'Criar regra':'Adicionar IP à resposta';f.querySelector('button[type="submit"]').textContent=type==='device'?'Adicionar':type==='rule'?'Criar regra':'Adicionar com expiração';$('#'+type+'-cancel').hidden=true}
for(const type of ['device','rule','block'])$('#'+type+'-cancel').onclick=()=>cancelRecordEdit(type);

let ruleSample='';
const ruleExamples={
 ssh:{name:'Tentativas repetidas de acesso SSH',kind:'any',pattern:'(?i)(failed password|authentication failure|authentication failed|invalid user)',threshold:5,window_seconds:120,level:10},
 firewall:{name:'Bloqueios repetidos no pfSense',kind:'pfsense',pattern:'filterlog.*,(block|reject),',threshold:30,window_seconds:60,level:8},
 disk:{name:'Falha de disco ou armazenamento',kind:'proxmox',pattern:'(?i)(I/O error|ata.*error|nvme.*(error|failed)|filesystem.*error|smart.*failed)',threshold:1,window_seconds:60,level:12},
 hardware:{name:'Temperatura ou falha de hardware',kind:'any',pattern:'(?i)(critical temperature|thermal.*critical|machine check|hardware error|uncorrectable.*error)',threshold:1,window_seconds:60,level:13}
};
function draftRule(values){cancelRecordEdit('rule');ruleSample='';goto('rules');const f=$('#rule-form');for(const [key,value] of Object.entries(values))if(f.elements[key])f.elements[key].value=value;f.elements.id.value='regra-'+Date.now().toString(36);f.elements.block.checked=false;f.elements.kind.dispatchEvent(new Event('change'));f.scrollIntoView({behavior:'smooth',block:'center'});f.elements.name.focus();toast('Rascunho preenchido. Revise e clique em Criar regra para salvar.');}
$('#rule-example-use').onclick=()=>{const example=ruleExamples[$('#rule-example').value];if(!example){toast('Selecione um exemplo');return}draftRule(example)};
function literalRulePattern(message){return String(message).slice(0,120).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function draftRuleFromEvent(event){
 const message=event.message||'',known=/failed password|authentication fail|invalid user/i.test(message)?ruleExamples.ssh:/filterlog.*,(block|reject),/.test(message)?ruleExamples.firewall:/I\/O error|filesystem.*error|smart.*failed/i.test(message)?ruleExamples.disk:null;
 const kind=['pfsense','proxmox','generic','unifi','snmp','webhook'].includes(event.kind)?event.kind:'any';
 draftRule({...known,name:'Detectar evento · '+(event.device||'dispositivo').slice(0,70),kind,pattern:known?known.pattern:literalRulePattern(message),threshold:known?known.threshold:1,window_seconds:known?known.window_seconds:60,level:known?known.level:10});ruleSample=message;$('#rule-event-context').hidden=false;$('#rule-event-preview').textContent=message;$('#rule-test-result').textContent=known?'Padrão sugerido a partir da categoria do evento.':'Padrão literal inicial: ajuste o trecho estável para detectar eventos semelhantes.';
}
$('#rule-test').onclick=async()=>{try{const f=$('#rule-form'),result=await api('/api/rules/test','POST',{pattern:f.elements.pattern.value,kind:f.elements.kind.value,message:ruleSample});$('#rule-test-result').textContent=(ruleSample?(result.sample_match?'Corresponde ao evento selecionado. ':'Não corresponde ao evento selecionado. '):'')+result.matches+' registros correspondentes entre '+result.checked+' registros recentes. Nenhuma regra foi salva.'}catch(error){$('#rule-test-result').textContent=error.message}};
