'use strict';
let assistantDialog=null,assistantRecognition=null,assistantVoiceTimer=null,assistantVoiceConsent=false,assistantBusy=false,assistantResult=null,assistantRequest=null,assistantAbort=null,assistantHistory=[];
function assistantContext(){
 const data={page,client:page==='events'?eventClientSelection:'',captured:new Date().toISOString()};
 const events=page==='events'?(historyEventsData?.events||[]):page==='overview'?(snapshot?.critical_events||[]):[];
 data.events=events.slice(0,6).map(e=>({time:e.time,device:e.device,message:String(e.message).slice(0,500),level:e.level,source_ip:e.source_ip}));
 if(page==='overview'){data.summary={events_today:snapshot?.total,alerts_in_memory:snapshot?.alerts};data.resources=[...document.querySelectorAll('[data-dashboard-card="resources"],[data-resource-copy]')].map(n=>({device:n.querySelector('select')?.selectedOptions[0]?.textContent,metrics:[...n.querySelectorAll('.resource-gauge')].map(x=>x.textContent)})).slice(0,8)}
 if(page==='reports'&&currentReport)data.report={filter:currentReport.filter,matched:currentReport.matched,critical:currentReport.critical,partial:currentReport.partial};
 if(page==='notifications'&&typeof hostHealthData!=='undefined')data.host=hostHealthData?.health;
 if(page==='devices')data.devices=(snapshot?.config?.devices||[]).slice(0,20).map(d=>({name:d.name,ip:d.ip,client:d.client,kind:d.kind}));
 if(page==='events')data.filters={query:$('#search').value,time_filter:historyTimeFilter,client:eventClientSelection,partial:historyEventsData?.partial,more:historyEventsData?.more};
 if(page==='network')data.network={mode:networkMode,devices:networkData.devices.slice(0,20).map(d=>({name:d.name,ip:d.ip,client:d.client,kind:d.kind})),tests:networkData.tests.slice(0,4).map(t=>({type:t.type,status:t.status,ip:t.ip,result:String(t.output||t.result||'').slice(0,500)}))};
 if(page==='rules')data.rules=(snapshot.rules||[]).slice(0,12).map(r=>({name:r.name,pattern:r.pattern,threshold:r.threshold,window_seconds:r.window_seconds,level:r.level,enabled:r.enabled}));
 if(page==='blocks')data.responses=(snapshot.blocks||[]).slice(0,12).map(b=>({ip:b.ip,reason:b.reason,mode:b.mode,expires:b.expires}));
 if(page==='settings')data.settings={model:snapshot.local_ai?.model,model_ready:snapshot.local_ai?.ready,auto_block:snapshot.config.auto_block,retention_days:snapshot.config.retention_days,max_daily_mb:snapshot.config.max_daily_mb};
 if(page==='receivers')data.integrations={model_ready:snapshot.local_ai?.ready,n8n_enabled:n8nData?.settings?.enabled};
 if(page==='backups')data.backups={drive_connected:snapshot.drive_connected,daily:snapshot.preferences?.backup_daily,time:snapshot.preferences?.backup_time,timezone:snapshot.preferences?.backup_timezone};
 if(page==='audit')data.audit=(snapshot.audit||[]).slice(-6).map(a=>({time:a.time,action:String(a.action).slice(0,300)}));
 return JSON.stringify(data).slice(0,6000);
}
function assistantMessage(root,title,text){const box=el('article',undefined,'assistant-message');box.append(el('strong',title),el('p',text));root.append(box);while(root.children.length>12)root.firstElementChild.remove();box.scrollIntoView({block:'nearest'});return box}
function assistantLocalDate(value){const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function stopAssistantVoice(){clearTimeout(assistantVoiceTimer);assistantRecognition?.abort();assistantRecognition=null;if(assistantDialog)assistantDialog.querySelector('.assistant-mic').textContent='🎙 Ditar pergunta'}
async function assistantVoice(textarea,status,button){
 if(assistantRecognition){stopAssistantVoice();status.textContent='Ditado encerrado. Revise o texto antes de enviar.';return}
 const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;
 if(!Recognition||!window.isSecureContext){status.textContent='Ditado indisponível neste navegador ou conexão. Use o campo de texto.';return}
 if(!assistantVoiceConsent){
  const consent=el('dialog',undefined,'assistant-consent'),allow=el('button','Concordo e ativar microfone'),cancel=el('button','Cancelar','secondary');consent.append(el('h2','Permitir ditado por voz?'),el('p','Seu navegador pode enviar o áudio ao provedor de reconhecimento de voz. O SIEM recebe somente a transcrição e não grava o áudio. Evite falar senhas ou outros segredos. A transcrição só será enviada ao Ollama após você revisar e clicar em Enviar.'),allow,cancel);document.body.append(consent);
  const granted=await new Promise(resolve=>{let ok=false;allow.onclick=()=>{ok=true;consent.close()};cancel.onclick=()=>consent.close();consent.onclose=()=>{consent.remove();resolve(ok)};consent.showModal()});
  if(!granted||!assistantDialog?.open)return;assistantVoiceConsent=true;
 }
 const recognition=new Recognition();assistantRecognition=recognition;recognition.lang='pt-BR';recognition.continuous=false;recognition.interimResults=false;recognition.maxAlternatives=1;
 recognition.onresult=e=>{const text=Array.from(e.results).map(r=>r[0].transcript).join(' ');textarea.value=(textarea.value+' '+text).trim().slice(0,2000);status.textContent='Transcrição pronta. Revise cliente, termo e período antes de enviar.';textarea.focus()};
 recognition.onerror=e=>{status.textContent='Não foi possível transcrever ('+e.error+'). Você pode digitar a pergunta.'};
 recognition.onend=()=>{clearTimeout(assistantVoiceTimer);if(assistantRecognition===recognition)assistantRecognition=null;button.textContent='🎙 Ditar pergunta'};
 try{recognition.start();button.textContent='■ Parar ditado';status.textContent='Ouvindo por até 30 segundos…';assistantVoiceTimer=setTimeout(()=>recognition.stop(),30000)}catch{stopAssistantVoice();status.textContent='Microfone indisponível. Confira a permissão do navegador.'}
}
function assistantDownload(result){const blob=new Blob([JSON.stringify(result,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='relatorio-siem-ia.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function assistantPrint(result){const old=$('#assistant-print');old?.remove();const root=el('section',undefined,'assistant-print');root.id='assistant-print';buildAssistantEvidence(root,result,true);document.body.append(root);document.body.classList.add('printing-assistant');window.print()}
window.addEventListener('afterprint',()=>{document.body.classList.remove('printing-assistant');$('#assistant-print')?.remove()});
function buildAssistantEvidence(root,r,print=false){
 root.append(el('h3','Consulta do SIEM'),el('p','Cliente: '+(r.filter.client==='~unassigned'?'Sem cliente':r.filter.client||'Todos')+' · '+date(r.filter.from)+' a '+date(r.filter.to)+' · Termo: '+(r.filter.query||'Todos')+' · '+(r.filter.critical?'Somente críticos':'Todos os níveis')));
 root.append(el('small','Logs originais e alertas derivados são registros distintos. Totais referem-se aos registros consultados, sujeitos à retenção.'),el('p',r.matched+' registros '+(r.report?'no relatório':'nesta página')+' · '+r.critical+' críticos · Gerado em '+date(r.generated)));
 root.append(el('p',r.partial||r.more?'Resultado parcial. Há mais registros ou um limite de leitura foi atingido. Reduza o intervalo para obter um relatório completo.':'Consulta concluída dentro dos limites de leitura. Ausência de registros pode refletir retenção ou ausência de coleta.','assistant-limit'));
 if(r.answer)root.append(el('strong','Hipótese da IA local · '+r.model),el('p',r.answer,'assistant-answer'));if(r.analysis_error)root.append(el('p',r.analysis_error+'; os dados consultados foram preservados.'));
 const stats=el('div',undefined,'assistant-stats');Object.entries(r.by_device||{}).slice(0,50).forEach(([name,count])=>stats.append(el('span',name+': '+count)));root.append(stats);
 if(r.ips?.length)root.append(el('p','IPs em eventos críticos: '+r.ips.slice(0,50).map(x=>x.ip+' ('+x.count+')').join(', ')));
 const list=el('div',undefined,'assistant-evidence');for(const e of r.events.slice(0,print?100:100)){const row=el('article');row.append(el('small',date(e.time)+' · '+e.device+' · Nível '+e.level+' · IP '+(e.source_ip||'—')),el('p',e.message));list.append(row)}root.append(list);
 if(r.events.length>100)root.append(el('p','Exibição e PDF limitados a 100 registros; o JSON contém os '+r.events.length+' registros consultados.'));
}
async function runAssistantQuery(request,root,status){
 if(assistantBusy)return;assistantBusy=true;assistantRequest=request;status.textContent=request.report?'Consultando o histórico e gerando o relatório…':'Consultando o histórico…';assistantAbort=new AbortController();
 try{const result=await assistantFetch('/api/assistant/query',request);assistantResult=result;root.replaceChildren();buildAssistantEvidence(root,result);const buttons=el('div',undefined,'toolbar'),download=el('button','Baixar JSON','secondary'),pdf=el('button','PDF / imprimir','secondary');download.onclick=()=>assistantDownload(result);pdf.onclick=()=>assistantPrint(result);buttons.append(download,pdf);
  if(!request.report){for(const [label,offset]of [['Mais recentes',Math.max(0,request.offset-100)],['Mais antigos',request.offset+100]]){const b=el('button',label,'secondary');b.disabled=label==='Mais recentes'?request.offset===0:!result.more;b.onclick=()=>runAssistantQuery({...request,offset},root,status);buttons.append(b)}}root.append(buttons);const conversation=root.closest('.assistant-conversation');if(conversation)conversation.scrollTop+=root.getBoundingClientRect().top-conversation.getBoundingClientRect().top;status.textContent=result.analysis_error?'Consulta concluída; IA indisponível.':request.report?'Relatório pronto para revisão.':'Resultados carregados.';
 }catch(error){if(error.name!=='AbortError')status.textContent=error.message}finally{assistantBusy=false;assistantAbort=null}
}
async function assistantFetch(path,body){const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':snapshot?.csrf||''},body:JSON.stringify(body),signal:assistantAbort?.signal});if(response.status===401){location.href='/';throw Error('Sessão expirada')}if(!response.ok)throw Error(await response.text());return response.json()}
function showAssistantPlan(root,data,question,status){
 const p=data.plan;if(p.action==='answer'||p.action==='clarify'){assistantMessage(root,'IA local · '+data.model,p.answer);return}
 const box=assistantMessage(root,'Confirme a consulta · '+data.model,p.answer||'Revise os filtros antes de consultar.'),form=el('form',undefined,'assistant-filter'),client=el('select'),query=el('input'),from=el('input'),to=el('input'),critical=el('input'),submit=el('button',p.action==='report'?'Gerar relatório':'Buscar logs');
 client.append(new Option('Todos os clientes',''),new Option('Sem cliente atribuído','~unassigned'));data.clients.forEach(name=>client.append(new Option(name,name)));client.value=p.client;query.value=p.query;query.maxLength=128;query.type='search';from.type=to.type='datetime-local';from.required=to.required=true;const end=new Date(Date.now()-60000);to.value=assistantLocalDate(end);from.value=assistantLocalDate(new Date(end.getTime()-p.hours*3600000));critical.type='checkbox';critical.checked=p.critical;
 for(const [title,field]of [['Cliente',client],['Palavra-chave ou IP',query],['De (data e hora)',from],['Até (data e hora)',to],['Somente críticos',critical]]){const label=el('label',title);label.append(field);form.append(label)}form.append(submit);box.append(form);
 form.onsubmit=async e=>{e.preventDefault();if(assistantBusy)return;const start=new Date(from.value),end=new Date(to.value);if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||start>=end||end>Date.now()||end-start>31*86400000){status.textContent='Escolha um intervalo passado de até 31 dias.';return}submit.disabled=true;const output=el('div');box.append(output);await runAssistantQuery({filter:{client:client.value,query:query.value,from:start.toISOString(),to:end.toISOString(),critical:critical.checked},report:p.action==='report',offset:0,question},output,status);submit.disabled=false};
}
function openAssistant(){
 if(assistantDialog?.open)return;if(!snapshot){toast('Aguarde a conexão com o SIEM.');return}
 const dialog=el('dialog',undefined,'assistant-dialog'),heading=el('div',undefined,'assistant-heading'),close=el('button','Fechar','secondary'),clear=el('button','Limpar conversa','secondary'),root=el('div',undefined,'assistant-conversation'),form=el('form',undefined,'assistant-composer'),label=el('label','Sua pergunta'),question=el('textarea'),send=el('button','Enviar'),mic=el('button','🎙 Ditar pergunta','secondary assistant-mic'),context=el('input'),contextLabel=el('label','Incluir dados da página atual'),status=el('p','Modelo selecionado: '+(snapshot.local_ai?.model||'—')+' · respostas para revisão.','assistant-status');
 assistantDialog=dialog;assistantResult=null;assistantRequest=null;assistantHistory=[];dialog.setAttribute('aria-labelledby','assistant-title');const title=el('h2','Pergunte à IA');title.id='assistant-title';heading.append(title,clear,close);dialog.append(heading,el('p','Consulte logs ou gere um relatório por cliente. A IA só interpreta os dados; nenhuma alteração é executada.'),root,form,status);status.setAttribute('role','status');question.rows=3;question.maxLength=2000;question.required=true;question.placeholder='Ex.: Gere um relatório do cliente Multipla com attack nas últimas 24 horas';label.append(question);context.type='checkbox';context.checked=true;contextLabel.prepend(context);mic.type=clear.type=close.type='button';form.append(label,contextLabel,mic,send);document.body.append(dialog);close.onclick=()=>dialog.close();clear.onclick=()=>{if(assistantBusy)return;root.replaceChildren();question.value='';assistantHistory=[];assistantResult=null;assistantRequest=null};mic.onclick=()=>assistantVoice(question,status,mic);
 if(!(window.SpeechRecognition||window.webkitSpeechRecognition)||!window.isSecureContext){mic.disabled=true;mic.title='Reconhecimento de voz indisponível neste navegador ou conexão'}
 dialog.onclose=()=>{stopAssistantVoice();assistantAbort?.abort();dialog.remove();assistantDialog=null;assistantHistory=[];assistantResult=null;assistantRequest=null};document.addEventListener('visibilitychange',()=>{if(document.hidden)stopAssistantVoice()},{signal:(()=>{const c=new AbortController();dialog.addEventListener('close',()=>c.abort(),{once:true});return c.signal})()});
 form.onsubmit=async e=>{e.preventDefault();if(assistantBusy)return;stopAssistantVoice();const text=question.value.trim();if(!text)return;assistantBusy=true;send.disabled=mic.disabled=true;status.textContent='Interpretando seu pedido no Ollama…';assistantMessage(root,'Você',text);assistantAbort=new AbortController();
  try{const data=await assistantFetch('/api/assistant/plan',{question:text,history:JSON.stringify(assistantHistory).slice(0,6000),page,client:page==='events'?eventClientSelection:'',context:context.checked?assistantContext():''});assistantHistory.push({question:text.slice(0,1000),answer:data.plan.answer.slice(0,1000),filters:{action:data.plan.action,client:data.plan.client,query:data.plan.query,hours:data.plan.hours,critical:data.plan.critical}});assistantHistory=assistantHistory.slice(-2);showAssistantPlan(root,data,text,status);question.value='';status.textContent='Modelo utilizado: '+data.model+' · '+(data.plan.action==='clarify'?'Esclareça o pedido no campo abaixo.':'Revise a resposta ou os filtros.')}catch(error){if(error.name!=='AbortError')status.textContent=error.message}finally{assistantBusy=false;assistantAbort=null;send.disabled=false;mic.disabled=!(window.SpeechRecognition||window.webkitSpeechRecognition)||!window.isSecureContext}
 };dialog.showModal();question.focus();
}
$('#ask-ai').onclick=openAssistant;
