'use strict';
const deviceNetworkCache=new Map(),deviceNetworkBusy=new Set();
function displayDeviceNetworkResult(card,info){const result=el('div',undefined,'device-network-result');card.querySelector('.device-network-result')?.remove();for(const [label,key]of [['Hostname (DNS reverso)','hostname'],['MAC cadastrado','mac'],['Vizinhança de rede observada','neighbors'],['Portas TCP selecionadas','ports'],['Compartilhamentos SMB sem credenciais','shares']]){const item=el('details');preserveDeviceDetail(item,info.ip||card.dataset.deviceIP,label);item.append(el('summary',label),el('pre',info[key]||'Não disponível','network-output'));result.append(item)}result.append(el('p',info.note));card.append(result)}
function appendDeviceNetworkActions(card,d){
 card.append(el('p',[d.client,d.unit].filter(Boolean).join(' / ')),el('p',d.mac?'MAC cadastrado: '+d.mac:'MAC não cadastrado'));
 const inspect=el('button','Consultar detalhes de rede','secondary');inspect.type='button';inspect.disabled=deviceNetworkBusy.has(d.ip);if(deviceNetworkCache.has(d.ip))displayDeviceNetworkResult(card,deviceNetworkCache.get(d.ip));inspect.onclick=async()=>{deviceNetworkBusy.add(d.ip);
  inspect.disabled=true;const result=el('div',undefined,'device-network-result');card.querySelector('.device-network-result')?.remove();card.append(result);result.append(el('p','Consultando hostname, portas e compartilhamentos SMB…'));
  try{const info=await api('/api/devices/network','POST',{ip:d.ip,action:'inspect'});deviceNetworkCache.set(d.ip,info);displayDeviceNetworkResult(card,info);}catch(e){result.replaceChildren(el('p',e.message))}finally{deviceNetworkBusy.delete(d.ip);inspect.disabled=false;if(page==='devices')render()}
 };card.append(inspect);
 const wake=el('button','Wake-on-LAN','secondary');wake.type='button';wake.disabled=!d.mac||!d.wol_target;wake.title=wake.disabled?'Cadastre MAC e destino de envio para habilitar':'Enviar pacote Wake-on-LAN';wake.onclick=()=>run(async()=>{if(!confirm('Enviar Wake-on-LAN para '+d.name+'?'))return;const res=await api('/api/devices/network','POST',{ip:d.ip,action:'wake'});toast(res.result)});card.append(wake);
}
let rebootStatusTimer;
$('#server-reboot').onclick=()=>{
 const dialog=el('dialog'),form=el('form'),heading=el('h2','Confirmar reinício do servidor'),description=el('p','Esta VM Linux será reiniciada. O painel e a coleta ficarão temporariamente indisponíveis. O tempo de retorno depende do servidor.'),label=el('label','Digite REINICIAR para confirmar'),input=el('input'),cancel=el('button','Cancelar','secondary'),submit=el('button','Confirmar reboot'),feedback=el('p');
 input.autocomplete='off';input.required=true;input.setAttribute('aria-label','Confirmação de reinício');label.append(input);cancel.type='button';submit.type='submit';submit.disabled=true;input.oninput=()=>submit.disabled=input.value!=='REINICIAR';cancel.onclick=()=>dialog.close();form.append(heading,description,label,cancel,submit,feedback);dialog.append(form);document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove(),{once:true});dialog.showModal();input.focus();
 form.onsubmit=async event=>{
  event.preventDefault();if(input.value!=='REINICIAR')return;submit.disabled=true;cancel.disabled=true;input.disabled=true;feedback.textContent='Solicitando reinício…';const button=$('#server-reboot'),status=$('#server-reboot-status');button.disabled=true;
  try{
   await api('/api/system/reboot','POST',{confirm:'REINICIAR'});dialog.close();const started=Date.now();clearInterval(rebootStatusTimer);
   const update=()=>{const seconds=Math.floor((Date.now()-started)/1000);status.textContent='Reinício aceito pelo sistema · '+seconds+' segundos decorridos. Aguarde o servidor voltar e recarregue o painel.';if(seconds>=300){clearInterval(rebootStatusTimer);status.textContent+=' Se o painel não retornar, verifique a VM pelo console.'}};update();rebootStatusTimer=setInterval(update,1000);
  }catch(error){status.textContent='Não foi possível confirmar o reinício: '+error.message+'. Se a conexão caiu, verifique a VM antes de tentar novamente.';feedback.textContent=status.textContent;cancel.disabled=false;input.disabled=false;submit.disabled=false;button.disabled=false}
 };
};
const expandedDashboardAlerts=new Set();
function renderCompactAlerts(events){
 const root=$('#recent-alerts'),position=root.scrollTop;root.replaceChildren();if(!events.length){root.append(el('div','Nenhum alerta nesta janela.','empty'));return}
 for(const e of events){const item=el('details',undefined,'compact-alert'),summary=el('summary'),title=el('span',e.review?.title||e.rule||'Alerta','compact-alert-title');item.open=expandedDashboardAlerts.has(e.id);item.addEventListener('toggle',()=>{if(item.isConnected){if(item.open)expandedDashboardAlerts.add(e.id);else expandedDashboardAlerts.delete(e.id)}});title.append(el('small',(e.device||'Origem não identificada')+' · '+(e.source_ip||e.source||'IP não identificado')));summary.append(badge(e.review?.level||e.level),title,el('time',new Date(e.time).toLocaleTimeString('pt-BR'),'compact-alert-time'));item.append(summary);const content=el('div',undefined,'compact-alert-detail');const row=eventRows([e])[0];for(const cell of [row[2],row[5]])if(cell instanceof Node)content.append(cell);item.append(content);root.append(item)}root.scrollTop=position;
}
function renderDeviceDonut(series){
 const box=$('#device-donut');if(!box)return;box.replaceChildren();const active=series.filter(g=>g.total>0),total=active.reduce((n,g)=>n+g.total,0);box.append(el('h3','Logs por dispositivo'),el('p',dashboardDistributionLabel));
 if(!total){box.append(el('p','Aguardando logs para compor o gráfico.'));return}
 const rows=active.slice(0,5);if(active.length>5)rows.push({name:'Outros dispositivos',total:active.slice(5).reduce((n,g)=>n+g.total,0)});
 const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 180 180');svg.setAttribute('role','img');svg.setAttribute('aria-label','Distribuição da amostra por dispositivo');let offset=0;const circumference=2*Math.PI*65;
 const body=el('div',undefined,'donut-body'),legend=el('div',undefined,'donut-legend');rows.forEach((g,i)=>{const c=document.createElementNS(ns,'circle');for(const [k,v]of Object.entries({cx:90,cy:90,r:65,fill:'none',stroke:activityColors[i],'stroke-width':18,'stroke-dasharray':(g.total/total*circumference)+' '+circumference,'stroke-dashoffset':-offset,transform:'rotate(-90 90 90)'}))c.setAttribute(k,v);offset+=g.total/total*circumference;const t=document.createElementNS(ns,'title');t.textContent=g.name+': '+g.total;c.append(t);svg.append(c);const row=el('div'),dot=el('i');dot.style.background=activityColors[i];row.append(dot,el('span',g.name),el('b',g.total.toLocaleString('pt-BR')+' · '+Math.round(g.total/total*100)+'%'));legend.append(row)});
 const text=document.createElementNS(ns,'text');text.setAttribute('x','90');text.setAttribute('y','95');text.setAttribute('text-anchor','middle');text.setAttribute('fill','#e9f1fc');text.setAttribute('font-size','23');text.textContent=total.toLocaleString('pt-BR');svg.append(text);body.append(svg,legend);box.append(body);
}

let dashboardDistributionLabel='Últimas 24h · consultando histórico…',dashboardDistribution=null,dashboardDistributionTime=0,dashboardDistributionBusy=false;
async function updateDashboardDistribution(){
 if(dashboardDistributionBusy||Date.now()-dashboardDistributionTime<60000)return;dashboardDistributionBusy=true;
 try{const data=await api('/api/dashboard/distribution');dashboardDistribution=Object.entries(data.by_device||{}).map(([name,total])=>({name:name||'Origem não identificada',total})).sort((a,b)=>b.total-a.total);dashboardDistributionTime=Date.now();dashboardDistributionLabel='Últimas 24 horas · logs originais'+(data.partial?' · leitura parcial (limite atingido)':'')+(data.missing_days?.length?' · há dias sem arquivo disponível':'');renderDeviceDonut(dashboardDistribution)}catch(e){dashboardDistributionLabel='Histórico indisponível · amostra em memória dos últimos 30 min';renderDeviceDonut(deviceActivitySeries(snapshot?.events,snapshot?.config.devices))}finally{dashboardDistributionBusy=false}
}

let deviceMetricsSnapshot={},deviceMetricsFetched=0;
async function refreshDeviceMetrics(){try{deviceMetricsSnapshot=await api('/api/devices/metrics');deviceMetricsFetched=Date.now();if(page==='devices'||page==='overview')render()}catch{}}
function appendCollectorActions(card,d){
 const metrics=deviceMetricsSnapshot[d.ip];if(d.kind!=='windows'&&d.kind!=='linux'&&!metrics)return;const box=el('div',undefined,'device-metrics');
 if(metrics){const stale=Date.now()-Date.parse(metrics.received)>180000;box.append(el('p',(stale?'Métricas desatualizadas':'Métricas recebidas')+' · '+date(metrics.received)),el('p','Hostname: '+metrics.hostname));for(const [name,value]of [['CPU',metrics.cpu],['Memória',metrics.memory],...(metrics.disks||[]).map(x=>['Disco '+x.drive,x.used_percent])]){const row=el('div',undefined,'metric-resource'),label=el('span',name+' · '+Number(value).toFixed(1)+'%'),bar=el('meter');bar.min=0;bar.max=100;bar.low=70;bar.high=90;bar.optimum=20;bar.value=value;bar.setAttribute('aria-label',name);row.append(label,bar);box.append(row)}box.append(el('p','Rede: ↓ '+(metrics.receive_bytes_per_second/1024).toFixed(1)+' KB/s · ↑ '+(metrics.send_bytes_per_second/1024).toFixed(1)+' KB/s'))}else box.append(el('p','CPU, memória, disco e rede: aguardando coletor.'));card.append(box);if(Date.now()-deviceMetricsFetched>60000){deviceMetricsFetched=Date.now();refreshDeviceMetrics()}if(snapshot?.role==='viewer')return;
 const key=el('button','Gerar chave do coletor','secondary');key.type='button';key.onclick=()=>run(async()=>{
  if(!confirm('Gerar uma chave exclusiva para '+d.name+'? A chave anterior será revogada.'))return;const response=await api('/api/devices/metrics-key','POST',{ip:d.ip});
  const dialog=el('dialog'),close=el('button','Fechar');dialog.append(el('h2','Chave exclusiva · '+d.name),el('p',response.note));const text=el('textarea');text.value=response.key;text.readOnly=true;text.setAttribute('aria-label','Chave do coletor');dialog.append(text,el('p',d.kind==='linux'?'Execute sudo bash ./linux-collector-install.sh. O instalador solicita o endereço HTTPS do SIEM, o IP cadastrado e a chave individual sem exibi-la.':'Baixe o coletor e execute como administrador: powershell -NoProfile -File .\\windows-collector.ps1 -Install -Server "'+snapshot.config.public_url+'" -DeviceIP "'+d.ip+'". A chave será solicitada sem aparecer na linha de comando.'),close);document.body.append(dialog);close.onclick=()=>dialog.close();dialog.addEventListener('close',()=>{text.value='';dialog.remove()},{once:true});dialog.showModal();text.focus();text.select();
 });const revoke=el('button','Revogar coletor','secondary');revoke.type='button';revoke.onclick=()=>run(async()=>{if(!confirm('Revogar o envio de métricas de '+d.name+'?'))return;await api('/api/devices/metrics-key','POST',{ip:d.ip,revoke:true});toast('Chave revogada.')});const download=el('a','Baixar coletor '+(d.kind==='linux'?'Linux':'Windows'),'button secondary');download.href='/api/devices/collector?platform='+(d.kind==='linux'?'linux':'windows');download.download=d.kind==='linux'?'linux-collector-install.sh':'windows-collector.ps1';card.append(key,revoke,download);
 if(Date.now()-deviceMetricsFetched>60000){deviceMetricsFetched=Date.now();refreshDeviceMetrics()}
}

const expandedDeviceCards=new Set(),expandedDeviceSections=new Set(),devicePingResults=new Map(),devicePingBusy=new Set();
function preserveDeviceDetail(node,ip,label){const key=ip+'|'+label;node.open=expandedDeviceSections.has(key);node.addEventListener('toggle',()=>{if(!node.isConnected)return;if(node.open)expandedDeviceSections.add(key);else expandedDeviceSections.delete(key)})}
function renderCompactDevices(s,devices,readOnly){
 const grid=$('#device-list');grid.replaceChildren();
 devices.forEach((d,index)=>{
  const card=el('article',undefined,'device-card compact-device-card');card.dataset.deviceIP=d.ip;
  const seen=s.last_seen?.[d.name],tracked=Object.hasOwn(s.device_presence||{},d.ip),online=tracked?s.device_presence[d.ip]:deviceHasRecentEvent(seen);
  card.append(el('span',tracked?(online?'Online · Tailscale':'Offline · Tailscale'):(online?'Online · eventos':'Sem eventos recentes'),'badge '+(online?'device-online':'device-offline')),el('h2',d.name),el('p',d.kind+' · '+d.ip));
  const metrics=deviceMetricsSnapshot[d.ip];if(metrics){const summary=el('div',undefined,'device-metric-summary');for(const [label,value] of [['CPU',metrics.cpu],['Memória',metrics.memory]]){const item=el('span',label+' '+Number(value).toFixed(1)+'%');item.className=Number(value)>=90?'resource-danger':Number(value)>=70?'resource-warning':'resource-normal';summary.append(item)}card.append(summary,el('small',(Date.now()-Date.parse(metrics.received)>180000?'Métricas desatualizadas · ':'Atualizado · ')+date(metrics.received)))}else card.append(el('small',seen?'Último evento · '+date(seen):'Aguardando eventos ou coletor'));
  const toggle=el('button',expandedDeviceCards.has(d.ip)?'Ver menos':'Ver mais','secondary device-expand'),body=el('div',undefined,'device-expanded');toggle.type='button';body.hidden=!expandedDeviceCards.has(d.ip);toggle.setAttribute('aria-expanded',String(!body.hidden));toggle.onclick=()=>{body.hidden=!body.hidden;toggle.textContent=body.hidden?'Ver mais':'Ver menos';toggle.setAttribute('aria-expanded',String(!body.hidden));if(body.hidden)expandedDeviceCards.delete(d.ip);else expandedDeviceCards.add(d.ip)};card.append(toggle,body);
  body.append(el('p',[d.client,d.unit].filter(Boolean).join(' / ')),action('Editar',()=>startRecordEdit('device',d)),action('Remover',()=>api('/api/config','PUT',{...snapshot.config,devices:snapshot.config.devices.filter((_,i)=>i!==index)})));
  appendCollectorActions(body,d);body.dataset.deviceIP=d.ip;if(!readOnly){appendDeviceNetworkActions(body,d);appendDevicePing(body,d)}
  grid.append(card);
 });
}
function appendDevicePing(body,d){
 const button=el('button',devicePingBusy.has(d.ip)?'Ping em andamento…':'Pingar IP','secondary'),output=el('pre',devicePingResults.get(d.ip)||'','network-output');button.type='button';button.disabled=devicePingBusy.has(d.ip);output.hidden=!devicePingResults.has(d.ip);body.append(button,output);
 button.onclick=async()=>{devicePingBusy.add(d.ip);button.disabled=true;output.hidden=false;output.textContent='Enviando quatro pacotes ICMP a partir do SIEM…';try{const result=await api('/api/devices/network','POST',{ip:d.ip,action:'ping'});devicePingResults.set(d.ip,result.result);output.textContent=result.result}catch(error){devicePingResults.set(d.ip,error.message);output.textContent=error.message}finally{devicePingBusy.delete(d.ip);button.disabled=false}};
}

let dashboardResourceDevice='';
function resourceGauge(label,value){
 const card=el('div',undefined,'resource-gauge'),ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 120 120');svg.setAttribute('role','img');svg.setAttribute('aria-label',label+' '+Number(value).toFixed(1)+' por cento');
 const percent=Math.max(0,Math.min(100,Number(value))),color=percent>=90?'#ff8eab':percent>=70?'#ffbc66':'#53dec1',length=2*Math.PI*45;
 for(const active of [false,true]){const circle=document.createElementNS(ns,'circle');for(const [key,val]of Object.entries({cx:60,cy:60,r:45,fill:'none',stroke:active?color:'#253746','stroke-width':9,'stroke-linecap':'round',transform:'rotate(135 60 60)','stroke-dasharray':((active?percent/100:1)*length*.75)+' '+length}))circle.setAttribute(key,val);svg.append(circle)}
 const text=document.createElementNS(ns,'text');for(const [key,val]of Object.entries({x:60,y:66,'text-anchor':'middle',fill:color,'font-size':21,'font-weight':600}))text.setAttribute(key,val);text.textContent=percent.toFixed(1)+'%';svg.append(text);card.append(svg,el('b',label));return card;
}
function renderDashboardResources(s){
 for(const card of document.querySelectorAll('[data-dashboard-card="resources"],[data-resource-copy]'))renderResourceCard(s,card);
 if(Date.now()-deviceMetricsFetched>60000){deviceMetricsFetched=Date.now();refreshDeviceMetrics()}
}
function renderResourceCard(s,card){
 const role=id=>card.querySelector('#'+id)||card.querySelector('[data-resource-role="'+id+'"]'),id=card.dataset.dashboardCard;
 const select=role('dashboard-resource-device'),choices=(s.config.devices||[]).filter(d=>['windows','linux','proxmox'].includes(d.kind)||deviceMetricsSnapshot[d.ip]);select.replaceChildren();
 for(const d of choices){const option=el('option',d.name+' · '+d.ip);option.value=d.ip;select.append(option)}
 let ip=dashboardCardSettings[id]?.device||'';
 if(!choices.some(d=>d.ip===ip))ip=choices.find(d=>deviceMetricsSnapshot[d.ip])?.ip||choices[0]?.ip||'';select.value=ip;
 select.onchange=async()=>{const previous=structuredClone(dashboardCardSettings);dashboardCardSettings[id]={...(dashboardCardSettings[id]||{}),device:select.value};renderDashboardResources(snapshot);if(!dashboardEditing){try{await api('/api/dashboard/layout','PUT',{order:dashboardOrder(),cards:dashboardCardSettings});snapshot.preferences.dashboard_cards=structuredClone(dashboardCardSettings);dashboardAppliedKey=''}catch(error){dashboardCardSettings=previous;renderDashboardResources(snapshot);toast(error.message)}}};
 let stats=card.querySelector('.resource-statistics-button');if(!stats){stats=el('button','Exibir estatísticas de uso','secondary resource-statistics-button');stats.type='button';card.append(stats)}stats.onclick=()=>showResourceStatistics(select.value,choices.find(d=>d.ip===select.value)?.name||select.value);stats.disabled=!ip;
 const root=role('dashboard-resource-gauges'),network=role('dashboard-resource-network');root.replaceChildren();network.replaceChildren();const metric=deviceMetricsSnapshot[ip];
 if(metric){const stale=Date.now()-Date.parse(metric.received)>180000;role('dashboard-resource-status').textContent=(stale?'Métricas desatualizadas':'Coletor ativo')+' · '+metric.hostname+' · '+date(metric.received);root.append(resourceGauge('CPU',metric.cpu),resourceGauge('Memória',metric.memory),...(metric.disks||[]).slice(0,6).map(d=>resourceGauge('Disco '+d.drive,d.used_percent)));network.append(el('span','↓ Recepção '+(metric.receive_bytes_per_second/1024).toFixed(1)+' KB/s'),el('span','↑ Transmissão '+(metric.send_bytes_per_second/1024).toFixed(1)+' KB/s'),el('small','Taxa atual agregada das interfaces'));
 }else{role('dashboard-resource-status').textContent='Sem métricas recebidas para esta máquina';root.append(el('p','Cadastre uma máquina Windows/Linux e instale o coletor para acompanhar CPU, memória, discos e rede.','empty'))}
}

async function showResourceStatistics(ip,name){
 const dialog=el('dialog',undefined,'resource-statistics-dialog'),close=el('button','Fechar','secondary'),body=el('div'),title=el('h2','Estatísticas · '+name);dialog.setAttribute('aria-label','Estatísticas de recursos');close.onclick=()=>dialog.close();dialog.append(title,el('p','Últimas 24 horas · medições por minuto a partir do SIEM'),body,close);document.body.append(dialog);dialog.onclose=()=>dialog.remove();dialog.showModal();body.append(el('p','Consultando histórico…'));
 try{const data=await api('/api/devices/resource-history?ip='+encodeURIComponent(ip));if(!dialog.isConnected)return;body.replaceChildren();const samples=data.samples||[],metrics=samples.filter(s=>s.metrics),pings=samples.filter(s=>s.sent>0),sent=pings.reduce((n,s)=>n+s.sent,0),received=pings.reduce((n,s)=>n+s.received,0),latencies=pings.filter(s=>Number.isFinite(s.latency_avg_ms)),duration=samples.length?Math.min(24,(Date.parse(samples.at(-1).time)-Date.parse(samples[0].time)+60000)/3600000):0;
 body.append(el('p',samples.length?'Período observado: '+duration.toFixed(1)+' h · '+samples.length+' amostras · cobertura de coleta '+Math.min(100,samples.length/1440*100).toFixed(1)+'% das 24h.':'Histórico ainda vazio. A coleta começa após instalar esta versão.'));
 const rows=[];for(const [label,key]of [['CPU','cpu'],['Memória','memory']]){const values=metrics.map(s=>s.metrics[key]);if(values.length)rows.push([label,average(values).toFixed(1)+'%',Math.max(...values).toFixed(1)+'%',(100-average(values)).toFixed(1)+'%'])}
 const drives=[...new Set(metrics.flatMap(s=>s.metrics.disks||[]).map(d=>d.drive))];for(const drive of drives){const values=metrics.flatMap(s=>s.metrics.disks||[]).filter(d=>d.drive===drive).map(d=>d.used_percent);rows.push(['Disco '+drive,average(values).toFixed(1)+'%',Math.max(...values).toFixed(1)+'%',(100-average(values)).toFixed(1)+'%'])}
 body.append(el('p','Coletor com métricas recentes em '+(samples.length?(metrics.length/samples.length*100).toFixed(1):'0')+'% das amostras observadas. Recursos livres = 100% menos o uso médio; períodos sem métricas não entram na média.'));
 const table=el('table'),head=el('tr');['Recurso','Uso médio','Pico de uso','Livre médio'].forEach(t=>head.append(el('th',t)));table.append(head);rows.forEach(row=>{const tr=el('tr');row.forEach(t=>tr.append(el('td',t)));table.append(tr)});const wrapper=el('div',undefined,'statistics-table');wrapper.append(table);body.append(wrapper);
 const weightedLatency=latencies.reduce((n,s)=>n+s.latency_avg_ms*s.received,0),latencyPackets=latencies.reduce((n,s)=>n+s.received,0);
 body.append(el('h3','Rede · ping'),el('p',pings.length?'Disponibilidade ao ping: '+(pings.filter(s=>s.received>0).length/pings.length*100).toFixed(1)+'% das medições observadas.':'Disponibilidade ao ping: sem dados.'),el('p',sent?'Respostas: '+(received/sent*100).toFixed(1)+'% · Perda de pacotes: '+((sent-received)/sent*100).toFixed(1)+'% · '+received+' de '+sent+' pacotes.':'Nenhuma medição de ping disponível.'),el('p',latencyPackets?'Latência média: '+(weightedLatency/latencyPackets).toFixed(2)+' ms · máxima: '+Math.max(...latencies.map(s=>s.latency_max_ms)).toFixed(2)+' ms.':'Latência: sem respostas mensuráveis.'),el('p','Cobertura de ping: '+Math.min(100,pings.length/1440*100).toFixed(1)+'% das últimas 24h. Ausência de resposta pode indicar bloqueio de ICMP; não confirma falha da máquina.'));
 if(metrics.length)body.append(el('p','Tráfego médio observado: ↓ '+(average(metrics.map(s=>s.metrics.receive_bytes_per_second))/1024).toFixed(1)+' KB/s · ↑ '+(average(metrics.map(s=>s.metrics.send_bytes_per_second))/1024).toFixed(1)+' KB/s.'));
 renderResourceHistoryChart(body,samples);
 }catch(error){body.replaceChildren(el('p',error.message))}
}
function average(values){return values.reduce((n,v)=>n+v,0)/values.length}
function renderResourceHistoryChart(body,samples){
 const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 600 180');svg.setAttribute('role','img');svg.setAttribute('aria-label','Histórico observado de CPU e memória em percentual');svg.classList.add('resource-history-chart');
 if(!samples.length)return;for(const [value,y]of [[100,20],[50,90],[0,160]]){const line=document.createElementNS(ns,'line');for(const [k,v]of Object.entries({x1:20,x2:580,y1:y,y2:y,stroke:'#293845'}))line.setAttribute(k,v);svg.append(line);const text=document.createElementNS(ns,'text');text.setAttribute('x','0');text.setAttribute('y',String(y-2));text.setAttribute('font-size','10');text.setAttribute('fill','#8498ac');text.textContent=value+'%';svg.append(text)}const from=Date.parse(samples[0].time),span=Math.max(60000,Date.parse(samples.at(-1).time)-from);
 for(const [key,color]of [['cpu','#53dec1'],['memory','#ffbc66']]){let segments=[],points=[];let previous=0;const flush=()=>{if(points.length)segments.push(points.join(' '));points=[]};for(const s of samples){const t=Date.parse(s.time);if(!s.metrics||previous&&t-previous>120000){flush()}if(s.metrics)points.push((20+(t-from)/span*560).toFixed(1)+','+(160-s.metrics[key]*1.4).toFixed(1));previous=t}flush();for(const values of segments){const line=document.createElementNS(ns,'polyline');line.setAttribute('points',values);line.setAttribute('stroke',color);line.setAttribute('stroke-width',2);line.setAttribute('fill','none');svg.append(line)}}
 body.append(el('small',date(samples[0].time)+' → '+date(samples.at(-1).time)),el('p','Histórico de uso · CPU (verde) · memória (amarelo). Lacunas representam ausência de dados.'),svg);
}
