'use strict';
const deviceNetworkCache=new Map(),deviceNetworkBusy=new Set();
function displayDeviceNetworkResult(card,info){const result=el('div',undefined,'device-network-result');card.querySelector('.device-network-result')?.remove();for(const [label,key]of [['Hostname (DNS reverso)','hostname'],['MAC cadastrado','mac'],['Vizinhança de rede observada','neighbors'],['Portas TCP selecionadas','ports'],['Compartilhamentos SMB sem credenciais','shares']]){const item=el('details');item.append(el('summary',label),el('pre',info[key]||'Não disponível','network-output'));result.append(item)}result.append(el('p',info.note));card.append(result)}
function appendDeviceNetworkActions(card,d){
 card.append(el('p',[d.client,d.unit].filter(Boolean).join(' / ')),el('p',d.mac?'MAC cadastrado: '+d.mac:'MAC não cadastrado'));
 const inspect=el('button','Consultar detalhes de rede','secondary');inspect.type='button';inspect.disabled=deviceNetworkBusy.has(d.ip);if(deviceNetworkCache.has(d.ip))displayDeviceNetworkResult(card,deviceNetworkCache.get(d.ip));inspect.onclick=async()=>{deviceNetworkBusy.add(d.ip);
  inspect.disabled=true;const result=el('div',undefined,'device-network-result');card.querySelector('.device-network-result')?.remove();card.append(result);result.append(el('p','Consultando hostname, portas e compartilhamentos SMB…'));
  try{const info=await api('/api/devices/network','POST',{ip:d.ip,action:'inspect'});deviceNetworkCache.set(d.ip,info);displayDeviceNetworkResult(card,info);}catch(e){result.replaceChildren(el('p',e.message))}finally{deviceNetworkBusy.delete(d.ip);inspect.disabled=false;if(page==='devices')render()}
 };card.append(inspect);
 const wake=el('button','Wake-on-LAN','secondary');wake.type='button';wake.disabled=!d.mac||!d.wol_target;wake.title=wake.disabled?'Cadastre MAC e destino de envio para habilitar':'Enviar pacote Wake-on-LAN';wake.onclick=()=>run(async()=>{if(!confirm('Enviar Wake-on-LAN para '+d.name+'?'))return;const res=await api('/api/devices/network','POST',{ip:d.ip,action:'wake'});toast(res.result)});card.append(wake);
}
let rebootStatusTimer;
$('#server-reboot').onclick=()=>{
 const dialog=el('dialog'),form=el('form'),heading=el('h2','Confirmar reinício do servidor'),description=el('p','Esta VM Linux será reiniciada. O painel e a coleta ficarão temporariamente indisponíveis. O tempo de retorno depende do servidor.'),label=el('label','Digite REINICIAR para confirmar'),input=el('input'),cancel=el('button','Cancelar','secondary'),submit=el('button','Confirmar reboot'),feedback=el('p');
 input.autocomplete='off';input.required=true;input.setAttribute('aria-label','Confirmação de reinício');label.append(input);cancel.type='button';submit.type='submit';submit.disabled=true;input.oninput=()=>submit.disabled=input.value!=='REINICIAR';cancel.onclick=()=>dialog.close();form.append(heading,description,label,cancel,submit,feedback);dialog.append(form);document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove(),{once:true});dialog.showModal();input.focus();
 form.onsubmit=async event=>{
  event.preventDefault();if(input.value!=='REINICIAR')return;submit.disabled=true;cancel.disabled=true;input.disabled=true;feedback.textContent='Solicitando reinício…';const button=$('#server-reboot'),status=$('#server-reboot-status');button.disabled=true;
  try{
   await api('/api/system/reboot','POST',{confirm:'REINICIAR'});dialog.close();const started=Date.now();clearInterval(rebootStatusTimer);
   const update=()=>{const seconds=Math.floor((Date.now()-started)/1000);status.textContent='Reinício aceito pelo sistema · '+seconds+' segundos decorridos. Aguarde o servidor voltar e recarregue o painel.';if(seconds>=300){clearInterval(rebootStatusTimer);status.textContent+=' Se o painel não retornar, verifique a VM pelo console.'}};update();rebootStatusTimer=setInterval(update,1000);
  }catch(error){status.textContent='Não foi possível confirmar o reinício: '+error.message+'. Se a conexão caiu, verifique a VM antes de tentar novamente.';feedback.textContent=status.textContent;cancel.disabled=false;input.disabled=false;submit.disabled=false;button.disabled=false}
 };
};
const expandedDashboardAlerts=new Set();
function renderCompactAlerts(events){
 const root=$('#recent-alerts'),position=root.scrollTop;root.replaceChildren();if(!events.length){root.append(el('div','Nenhum alerta nesta janela.','empty'));return}
 for(const e of events){const item=el('details',undefined,'compact-alert'),summary=el('summary'),title=el('span',e.review?.title||e.rule||'Alerta','compact-alert-title');item.open=expandedDashboardAlerts.has(e.id);item.addEventListener('toggle',()=>{if(item.isConnected){if(item.open)expandedDashboardAlerts.add(e.id);else expandedDashboardAlerts.delete(e.id)}});title.append(el('small',(e.device||'Origem não identificada')+' · '+(e.source_ip||e.source||'IP não identificado')));summary.append(badge(e.review?.level||e.level),title,el('time',new Date(e.time).toLocaleTimeString('pt-BR'),'compact-alert-time'));item.append(summary);const content=el('div',undefined,'compact-alert-detail');const row=eventRows([e])[0];for(const cell of [row[2],row[5]])if(cell instanceof Node)content.append(cell);item.append(content);root.append(item)}root.scrollTop=position;
}
function renderDeviceDonut(series){
 const box=$('#device-donut');if(!box)return;box.replaceChildren();const active=series.filter(g=>g.total>0),total=active.reduce((n,g)=>n+g.total,0);box.append(el('h3','Logs por dispositivo'),el('p',dashboardDistributionLabel));
 if(!total){box.append(el('p','Aguardando logs para compor o gráfico.'));return}
 const rows=active.slice(0,5);if(active.length>5)rows.push({name:'Outros dispositivos',total:active.slice(5).reduce((n,g)=>n+g.total,0)});
 const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 180 180');svg.setAttribute('role','img');svg.setAttribute('aria-label','Distribuição da amostra por dispositivo');let offset=0;const circumference=2*Math.PI*65;
 const body=el('div',undefined,'donut-body'),legend=el('div',undefined,'donut-legend');rows.forEach((g,i)=>{const c=document.createElementNS(ns,'circle');for(const [k,v]of Object.entries({cx:90,cy:90,r:65,fill:'none',stroke:activityColors[i],'stroke-width':18,'stroke-dasharray':(g.total/total*circumference)+' '+circumference,'stroke-dashoffset':-offset,transform:'rotate(-90 90 90)'}))c.setAttribute(k,v);offset+=g.total/total*circumference;const t=document.createElementNS(ns,'title');t.textContent=g.name+': '+g.total;c.append(t);svg.append(c);const row=el('div'),dot=el('i');dot.style.background=activityColors[i];row.append(dot,el('span',g.name),el('b',g.total.toLocaleString('pt-BR')+' · '+Math.round(g.total/total*100)+'%'));legend.append(row)});
 const text=document.createElementNS(ns,'text');text.setAttribute('x','90');text.setAttribute('y','95');text.setAttribute('text-anchor','middle');text.setAttribute('fill','#e9f1fc');text.setAttribute('font-size','23');text.textContent=total.toLocaleString('pt-BR');svg.append(text);body.append(svg,legend);box.append(body);
}

let dashboardDistributionLabel='Últimas 24h · consultando histórico…',dashboardDistribution=null,dashboardDistributionTime=0,dashboardDistributionBusy=false;
async function updateDashboardDistribution(){
 if(dashboardDistributionBusy||Date.now()-dashboardDistributionTime<60000)return;dashboardDistributionBusy=true;
 try{const data=await api('/api/dashboard/distribution');dashboardDistribution=Object.entries(data.by_device||{}).map(([name,total])=>({name:name||'Origem não identificada',total})).sort((a,b)=>b.total-a.total);dashboardDistributionTime=Date.now();dashboardDistributionLabel='Últimas 24 horas · logs originais'+(data.partial?' · leitura parcial (limite atingido)':'')+(data.missing_days?.length?' · há dias sem arquivo disponível':'');renderDeviceDonut(dashboardDistribution)}catch(e){dashboardDistributionLabel='Histórico indisponível · amostra em memória dos últimos 30 min';renderDeviceDonut(deviceActivitySeries(snapshot?.events,snapshot?.config.devices))}finally{dashboardDistributionBusy=false}
}

let deviceMetricsSnapshot={},deviceMetricsFetched=0;
async function refreshDeviceMetrics(){try{deviceMetricsSnapshot=await api('/api/devices/metrics');deviceMetricsFetched=Date.now();if(page==='devices')render()}catch{}}
function appendCollectorActions(card,d){
 const metrics=deviceMetricsSnapshot[d.ip];if(d.kind!=='windows'&&d.kind!=='linux'&&!metrics)return;const box=el('div',undefined,'device-metrics');
 if(metrics){const stale=Date.now()-Date.parse(metrics.received)>180000;box.append(el('p',(stale?'Métricas desatualizadas':'Métricas recebidas')+' · '+date(metrics.received)),el('p','Hostname: '+metrics.hostname));for(const [name,value]of [['CPU',metrics.cpu],['Memória',metrics.memory],...(metrics.disks||[]).map(x=>['Disco '+x.drive,x.used_percent])]){const row=el('div',undefined,'metric-resource'),label=el('span',name+' · '+Number(value).toFixed(1)+'%'),bar=el('meter');bar.min=0;bar.max=100;bar.low=70;bar.high=90;bar.optimum=20;bar.value=value;bar.setAttribute('aria-label',name);row.append(label,bar);box.append(row)}box.append(el('p','Rede: ↓ '+(metrics.receive_bytes_per_second/1024).toFixed(1)+' KB/s · ↑ '+(metrics.send_bytes_per_second/1024).toFixed(1)+' KB/s'))}else box.append(el('p','CPU, memória, disco e rede: aguardando coletor.'));card.append(box);if(Date.now()-deviceMetricsFetched>60000){deviceMetricsFetched=Date.now();refreshDeviceMetrics()}if(snapshot?.role==='viewer')return;
 const key=el('button','Gerar chave do coletor','secondary');key.type='button';key.onclick=()=>run(async()=>{
  if(!confirm('Gerar uma chave exclusiva para '+d.name+'? A chave anterior será revogada.'))return;const response=await api('/api/devices/metrics-key','POST',{ip:d.ip});
  const dialog=el('dialog'),close=el('button','Fechar');dialog.append(el('h2','Chave exclusiva · '+d.name),el('p',response.note));const text=el('textarea');text.value=response.key;text.readOnly=true;text.setAttribute('aria-label','Chave do coletor');dialog.append(text,el('p',d.kind==='linux'?'Execute sudo bash ./linux-collector-install.sh. O instalador solicita o endereço HTTPS do SIEM, o IP cadastrado e a chave individual sem exibi-la.':'Baixe o coletor e execute como administrador: powershell -NoProfile -File .\\windows-collector.ps1 -Install -Server "'+snapshot.config.public_url+'" -DeviceIP "'+d.ip+'". A chave será solicitada sem aparecer na linha de comando.'),close);document.body.append(dialog);close.onclick=()=>dialog.close();dialog.addEventListener('close',()=>{text.value='';dialog.remove()},{once:true});dialog.showModal();text.focus();text.select();
 });const revoke=el('button','Revogar coletor','secondary');revoke.type='button';revoke.onclick=()=>run(async()=>{if(!confirm('Revogar o envio de métricas de '+d.name+'?'))return;await api('/api/devices/metrics-key','POST',{ip:d.ip,revoke:true});toast('Chave revogada.')});const download=el('a','Baixar coletor '+(d.kind==='linux'?'Linux':'Windows'),'button secondary');download.href='/api/devices/collector?platform='+(d.kind==='linux'?'linux':'windows');download.download=d.kind==='linux'?'linux-collector-install.sh':'windows-collector.ps1';card.append(key,revoke,download);
 if(Date.now()-deviceMetricsFetched>60000){deviceMetricsFetched=Date.now();refreshDeviceMetrics()}
}
