'use strict';
let hostUsageCache=null,hostUsageFetched=0,hostUsageBusy=false;
function hostDiskText(h){return Number.isFinite(h.disk_total_bytes)&&Number.isFinite(h.disk_free_bytes)?'Disco total: '+(h.disk_total_bytes/1073741824).toFixed(2)+' GiB · disponível: '+(h.disk_free_bytes/1073741824).toFixed(2)+' GiB':'Capacidade do disco: aguardando medição'}
function drawHostUsage(root,data){
 root.replaceChildren();root.append(el('strong','Uso nas últimas 24 horas'),el('small','CPU · RAM · Disco — médias de 15 minutos'));
 if(!data?.samples?.length){root.append(el('p','Histórico em formação. Sem medições anteriores à instalação.'));return}
 const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 480 145');svg.setAttribute('role','img');svg.setAttribute('aria-label','Uso de CPU, RAM e disco nas últimas 24 horas. Lacunas representam ausência de medição.');svg.classList.add('host-usage-chart');
 const start=Date.parse(data.from),end=Date.parse(data.to),buckets=Array.from({length:96},()=>({cpu:[],memory:[],disk:[]}));for(const s of data.samples){const i=Math.min(95,Math.floor((Date.parse(s.time)-start)/(end-start)*96));if(i<0)continue;for(const key of ['cpu','memory','disk'])if(Number.isFinite(s[key]))buckets[i][key].push(s[key])}
 for(const value of [0,50,100]){const y=115-value*.9,line=document.createElementNS(ns,'path');line.setAttribute('d','M30 '+y+' H470');line.setAttribute('class','host-usage-grid');svg.append(line);const text=document.createElementNS(ns,'text');text.setAttribute('x','0');text.setAttribute('y',y+4);text.textContent=value+'%';svg.append(text)}
 for(const [key,color]of [['cpu','#53dec1'],['memory','#79aefa'],['disk','#ffc574']]){let path='',active=false;for(let i=0;i<96;i++){const values=buckets[i][key];if(!values.length){active=false;continue}const value=values.reduce((a,b)=>a+b,0)/values.length,x=30+i/95*440,y=115-value*.9;path+=(active?' L':' M')+x.toFixed(1)+' '+y.toFixed(1);active=true;const dot=document.createElementNS(ns,'circle');dot.setAttribute('cx',x);dot.setAttribute('cy',y);dot.setAttribute('r','1.3');dot.setAttribute('fill',color);const title=document.createElementNS(ns,'title');title.textContent=key+' '+value.toFixed(1)+'% · '+date(new Date(start+(i+.5)/96*(end-start)).toISOString());dot.append(title);svg.append(dot)}const line=document.createElementNS(ns,'path');line.setAttribute('d',path);line.setAttribute('fill','none');line.setAttribute('stroke',color);line.setAttribute('stroke-width','1.8');svg.append(line)}
 for(const [x,label]of [[30,'24h atrás'],[235,'12h atrás'],[435,'Agora']]){const text=document.createElementNS(ns,'text');text.setAttribute('x',x);text.setAttribute('y','140');text.textContent=label;svg.append(text)}root.append(svg,el('small','CPU: verde · RAM: azul · Disco: amarelo. Lacunas = sem medição.'));
}
async function renderHostUsage(){const targets=[...document.querySelectorAll('.host-usage-container')];if(!targets.length)return;if(!hostUsageBusy&&Date.now()-hostUsageFetched>60000){hostUsageBusy=true;try{hostUsageCache=await api('/api/system/usage-history');hostUsageFetched=Date.now()}catch(error){targets.forEach(t=>t.replaceChildren(el('p',error.message)));return}finally{hostUsageBusy=false}}if(hostUsageCache)targets.forEach(t=>drawHostUsage(t,hostUsageCache))}
setInterval(()=>{if(document.visibilityState==='visible'&&(notificationDialog?.open||page==='notifications'))renderHostUsage()},60000);
