'use strict';
let hostHealthData=null,notificationData=null,hostHealthBusy=false,notificationDialog=null,hostHealthFetched=0;
function hostValue(value){return Number.isFinite(value)?value.toFixed(0)+'%':'—'}
async function refreshHostHealth(force=false){
 if(page==='notifications'&&hostHealthData)renderNotificationCenter();const needsNotifications=page==='notifications'&&!notificationData;if(!snapshot||hostHealthBusy||!force&&!needsNotifications&&Date.now()-hostHealthFetched<5000)return;hostHealthBusy=true;
 try{hostHealthData=await api('/api/system/health');hostHealthFetched=Date.now();renderHostHeader();if(page==='notifications'||notificationDialog?.open){notificationData=await api('/api/notifications');if(page==='notifications')renderNotificationCenter();if(notificationDialog?.open)renderNotificationPopup()}}
 catch(error){const button=$('#host-health-button');button.querySelector('i').className='host-health-dot unknown';$('#host-health-summary').textContent='Servidor: sem dados';button.title=error.message}
 finally{hostHealthBusy=false}
}
function renderHostHeader(){const h=hostHealthData.health||{},fresh=Date.now()-Date.parse(h.time)<20000,available=fresh&&[h.cpu,h.memory,h.disk].every(Number.isFinite),button=$('#host-health-button');$('#header-user').textContent=snapshot.email;$('#host-health-summary').textContent='CPU '+hostValue(h.cpu)+' · RAM '+hostValue(h.memory)+' · Disco '+hostValue(h.disk);button.querySelector('i').className='host-health-dot '+(h.high||h.error?'danger':available?'healthy':'unknown');button.classList.toggle('has-notifications',hostHealthData.unread>0);$('#notification-count').textContent=hostHealthData.unread||0;button.title=(h.error||'VM Linux do SIEM · alerta a partir de 90%')+(fresh?'':' · medição desatualizada');button.setAttribute('aria-label','Saúde do servidor. '+$('#host-health-summary').textContent+'. '+(hostHealthData.unread||0)+' notificações pendentes')}
function appendNotification(root,n,cleared){const row=el('article',undefined,'notification-item '+(n.severity==='critical'?'notification-critical':'')),pending=Date.parse(n.time)>Date.parse(cleared);row.append(el('strong',n.title),el('p',n.detail),el('small',date(n.time)+' · '+(pending?'Pendente':'Visualizada')));if(n.event_id){const link=el('button','Ver eventos','text-button');link.onclick=()=>{notificationDialog?.close();goto('events')};row.append(link)}root.append(row)}
function renderNotificationPopup(){if(!notificationData||!notificationDialog?.open)return;const root=notificationDialog.querySelector('.notification-popup-list'),scroll=root.scrollTop;root.replaceChildren();const pending=(notificationData.notifications||[]).filter(n=>Date.parse(n.time)>Date.parse(notificationData.cleared));if(!pending.length)root.append(el('p','Nenhuma notificação pendente.'));pending.slice(0,10).forEach(n=>appendNotification(root,n,notificationData.cleared));if(pending.length>10)root.append(el('p','Mais '+(pending.length-10)+' notificações na central.'));root.scrollTop=scroll;notificationDialog.querySelector('.notification-clear').disabled=!pending.length}
async function openNotificationPopup(){
 if(notificationDialog?.open)return;const dialog=el('dialog',undefined,'notification-dialog'),root=el('div',undefined,'notification-popup-list'),buttons=el('div',undefined,'toolbar'),center=el('button','Ir para central de notificações'),clear=el('button','Limpar notificações','secondary notification-clear'),close=el('button','Fechar','secondary');notificationDialog=dialog;dialog.setAttribute('aria-label','Notificações do SIEM');dialog.append(el('h2','Servidor e notificações'),el('p',$('#host-health-summary').textContent),root,buttons);buttons.append(center,clear,close);close.onclick=()=>dialog.close();center.onclick=()=>{dialog.close();goto('notifications');refreshHostHealth(true)};clear.onclick=()=>clearNotifications(clear);document.body.append(dialog);dialog.onclose=()=>{dialog.remove();notificationDialog=null};dialog.showModal();root.append(el('p','Consultando…'));try{notificationData=await api('/api/notifications');renderNotificationPopup()}catch(error){root.replaceChildren(el('p',error.message))}
}
async function clearNotifications(button){if(!notificationData)return;const pending=(notificationData.notifications||[]).filter(n=>Date.parse(n.time)>Date.parse(notificationData.cleared));if(!pending.length)return;const through=pending.reduce((latest,n)=>Date.parse(n.time)>Date.parse(latest)?n.time:latest,pending[0].time);button.disabled=true;try{await api('/api/notifications/clear','POST',{through});notificationData=await api('/api/notifications');renderNotificationPopup();if(page==='notifications')renderNotificationCenter();await refreshHostHealth(true)}catch(error){toast(error.message);button.disabled=false}}
function renderNotificationCenter(){const h=hostHealthData?.health||{},details=$('#host-health-details');details.replaceChildren();details.append(el('p','CPU '+hostValue(h.cpu)+' · RAM '+hostValue(h.memory)+' · Disco '+hostValue(h.disk)),el('p','Filesystem monitorado: '+(h.disk_path||'—')+' · atualizado '+(h.time?date(h.time):'—')));if(h.error)details.append(el('p',h.error));const root=$('#host-thread-list');root.replaceChildren();if(!h.threads?.length)root.append(el('p','Aguardando medição de processos no servidor Linux.'));else{const t=el('table'),head=el('tr');['PID / TID','Processo / thread','CPU','RAM compartilhada'].forEach(label=>head.append(el('th',label)));t.append(head);for(const item of h.threads){const tr=el('tr');[item.pid+' / '+item.tid,item.name,Number(item.cpu).toFixed(1)+'%',Number(item.memory_mb).toFixed(1)+' MB'].forEach(value=>tr.append(el('td',value)));t.append(tr)}root.append(t)}
 const list=$('#notifications-list');list.replaceChildren();if(!notificationData)list.append(el('p','Consultando notificações…'));else if(!notificationData.notifications?.length)list.append(el('p','Nenhuma notificação registrada.'));for(const n of notificationData?.notifications||[])appendNotification(list,n,notificationData.cleared);$('#notifications-clear').disabled=!notificationData?.unread;
}
$('#host-health-button').onclick=openNotificationPopup;$('#notifications-clear').onclick=()=>clearNotifications($('#notifications-clear'));
setInterval(()=>{if(document.visibilityState==='visible')refreshHostHealth()},5000);
